import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  content: { padding: 14, paddingBottom: 88, gap: 12 },
  flex: { flex: 1, minWidth: 0 },
  pageBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 4,
  },
  headingCopy: { flex: 1 },
  pageIconBox: {
    width: 48,
    height: 48,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#CCFBF1',
  },
  pageTitle: { color: '#0F172A', fontSize: 22, fontWeight: '800' },
  subtitle: { color: '#64748B', fontSize: 13, lineHeight: 19, marginTop: 2 },
  bookLocationButton: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#0D9488',
    borderRadius: 11,
  },
  bookLocationButtonText: { color: '#FFF', fontSize: 15, fontWeight: '800' },
  listPanel: {
    padding: 12,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    gap: 10,
  },
  panelHeading: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  panelTitle: { fontSize: 16, fontWeight: '800', color: '#0F172A' },
  iconAction: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    borderRadius: 9,
  },
  actionText: { fontSize: 12, fontWeight: '700', color: '#334155' },
  refreshed: { color: '#64748B', fontSize: 10 },
  columnsButton: {
    minHeight: 38,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 7,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  searchBox: {
    height: 42,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#FFF',
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 0,
    color: '#0F172A',
    fontSize: 12,
  },
  filterRow: { flexDirection: 'row', gap: 8 },
  inlineOptions: { maxHeight: 230, borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#FFF', borderRadius: 10, paddingHorizontal: 10, elevation: 2 },
  inlineOptionRow: { minHeight: 42, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  filterSelect: {
    flex: 1,
    minHeight: 40,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  selectText: { flex: 1, color: '#334155', fontSize: 12 },
  dateSelectText: { marginLeft: 2 },
  dateRangeRow: { flexDirection: 'row', gap: 8 },
  rangeDateTrigger: { flex: 1, minHeight: 40, paddingHorizontal: 8 },
  rangeDateText: { fontSize: 11 },
  card: {
    padding: 12,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#DDE5EC',
    borderRadius: 14,
    shadowColor: '#0F172A',
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
    position: 'relative',
    overflow: 'visible',
  },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  cardMenuOpen: { zIndex: 10, elevation: 10 },
  patientMark: {
    width: 38,
    height: 38,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#CCFBF1',
    backgroundColor: '#F0FDFA',
  },
  patientBlock: { flex: 1, minWidth: 0 },
  patientName: { color: '#0F172A', fontSize: 14, fontWeight: '800' },
  metaText: { color: '#64748B', fontSize: 11, marginTop: 3 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 20 },
  statusScheduled: { backgroundColor: '#E0F2FE' },
  statusActive: { backgroundColor: '#D1FAE5' },
  statusProgress: { backgroundColor: '#FEF3C7' },
  statusComplete: { backgroundColor: '#D1FAE5' },
  statusCancelled: { backgroundColor: '#FEE2E2' },
  statusText: { color: '#0369A1', fontSize: 9, fontWeight: '800' },
  statusTextActive: { color: '#047857' },
  statusTextCancelled: { color: '#B91C1C' },
  moreButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  cardDetails: {
    marginTop: 10,
    paddingTop: 9,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    gap: 8,
  },
  detailRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  detailText: { flex: 1, color: '#475569', fontSize: 12, lineHeight: 17 },
  reasonLabel: { width: 50, color: '#64748B', fontSize: 11, fontWeight: '700' },
  modeText: { color: '#0F766E', fontSize: 11, fontWeight: '700' },
  shareButton: { alignSelf: 'flex-start', marginTop: 2, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 8, backgroundColor: '#F0FDFA', borderWidth: 1, borderColor: '#CCFBF1' },
  shareButtonText: { color: '#0F766E', fontSize: 11, fontWeight: '700' },
  callButton: {
    minHeight: 39,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 9,
    backgroundColor: '#0D9488',
  },
  callButtonText: { color: '#FFF', fontSize: 12, fontWeight: '800' },
  empty: { alignItems: 'center', paddingVertical: 30, gap: 8 },
  emptyText: { color: '#64748B', textAlign: 'center', fontSize: 13 },
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.40)',
    justifyContent: 'center',
    padding: 20,
  },
  optionPanel: {
    width: '100%',
    maxWidth: 380,
    alignSelf: 'center',
    backgroundColor: '#FFF',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    elevation: 12,
  },
  appointmentMenu: {
    position: 'absolute',
    zIndex: 20,
    elevation: 12,
    top: 44,
    right: 4,
    width: 150,
    paddingHorizontal: 4,
    paddingVertical: 3,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    shadowColor: '#0F172A',
    shadowOpacity: 0.16,
    shadowRadius: 8,
  },
  optionHeader: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    marginBottom: 4,
  },
  optionTitle: { color: '#0F172A', fontSize: 15, fontWeight: '800' },
  optionRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  optionText: { color: '#334155', fontSize: 13, fontWeight: '600' },
  menuItem: {
    minHeight: 33,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  menuIconSlot: {
    width: 16,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuText: { flex: 1, fontSize: 12, fontWeight: '500', color: '#374151' },
  reschedulePanel: {
    width: '100%',
    maxWidth: 380,
    alignSelf: 'center',
    padding: 16,
    borderRadius: 15,
    backgroundColor: '#FFF',
  },
  detailsContent: { gap: 10, paddingVertical: 12 },
  detailsName: { color: '#0F172A', fontSize: 16, fontWeight: '800' },
  fieldLabel: {
    marginTop: 11,
    marginBottom: 5,
    color: '#475569',
    fontSize: 12,
    fontWeight: '700',
  },
  input: {
    height: 43,
    paddingHorizontal: 11,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#DCE4EC',
    color: '#0F172A',
  },
  primaryButton: {
    marginTop: 17,
    minHeight: 43,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#0D9488',
  },
  primaryText: { color: '#FFF', fontWeight: '800' },
  cancelButton: {
    marginTop: 8,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  cancelText: { color: '#334155', fontWeight: '700' },
  patientPicker: {
    maxHeight: '80%',
    padding: 14,
    backgroundColor: '#FFF',
    borderRadius: 14,
  },

  extractedInline1: { marginTop: 26 },
  extractedInline2: { maxHeight: 330 },
});
