import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  content: { padding: 14, paddingBottom: 60 },

  // Top Banner
  bannerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  bannerRowMobile: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    columnGap: 12,
    rowGap: 4,
  },
  bannerMobileIcon: { marginRight: 8 },
  headerActions: { alignItems: 'flex-end' },
  headerActionsMobile: {
    flexBasis: '100%',
    marginLeft: 52,
    alignItems: 'flex-start',
  },
  createClinicHeaderBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 6, backgroundColor: '#0D9488', borderRadius: 8,
    paddingHorizontal: 12, paddingVertical: 9,
  },
  createClinicHeaderText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  buildingIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#CCFBF1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerTitle: { fontSize: 24, fontWeight: '700', color: '#0F172A' },
  bannerSubtitle: { fontSize: 14, color: '#64748B', marginTop: 2 },

  upgradeLinkBtn: { paddingVertical: 4 },
  upgradeLinkText: { color: '#64748B', fontSize: 13, fontWeight: '500' },
  upgradeLinkHighlight: {
    color: '#0D9488',
    fontSize: 13,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },

  // Top Container Card
  topCardBorder: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 16,
    marginBottom: 16,
    elevation: 1,
  },

  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  controlsRowMobile: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 10,
    marginHorizontal: -16,
    marginTop: -16,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: '#F0FDFA',
    borderBottomColor: '#CCFBF1',
  },
  webDateTrigger: {
    minHeight: 44, borderRadius: 8, borderColor: '#99F6E4',
    backgroundColor: '#E6F4F1', paddingHorizontal: 12,
  },
  webDateTriggerText: { color: '#0D9488', fontSize: 14, fontWeight: '700' },
  controlLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
    marginBottom: 4,
    textTransform: 'uppercase',
  },

  controlSelectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
  },
  controlSelectBtnText: { color: '#0F172A', fontSize: 14, fontWeight: '600' },

  controlDropdownMenu: {
    position: 'absolute',
    top: 60,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingVertical: 4,
    elevation: 6,
    zIndex: 99,
  },
  controlDropdownMenuMobile: {
    position: 'relative',
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
    marginTop: 4,
    elevation: 2,
  },
  controlDropdownItem: { paddingHorizontal: 12, paddingVertical: 8 },
  controlDropdownItemText: { fontSize: 13, color: '#334155' },

  refreshCol: { flex: 1, alignItems: 'flex-end', justifyContent: 'center' },
  refreshDashBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  refreshDashBtnText: { color: '#334155', fontSize: 13, fontWeight: '600' },
  lastRefreshedText: { fontSize: 11, color: '#94A3B8', marginTop: 4 },

  sectionHeaderRow: { marginTop: 14, marginBottom: 12 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#0F172A' },
  sectionSubtitle: { fontSize: 12, color: '#64748B', marginTop: 2 },

  // KPI Grid 4
  kpiGrid4: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  kpiGrid3: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  dailyKpiGridMobile: {
    flexDirection: 'column',
    flexWrap: 'nowrap',
    justifyContent: 'flex-start',
    gap: 4,
  },

  kpiCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    backgroundColor: '#FFFFFF',
  },
  kpiCardDesktop: { width: '23.8%' },
  kpiCardDesktop3: { width: '32%' },
  kpiCardMobile: { width: '100%', padding: 14 },
  dailyKpiCardMobile: {
    width: '100%',
    padding: 15,
    alignItems: 'flex-start',
  },
  dailyKpiLabelMobile: { fontSize: 14, fontWeight: '600' },
  dailyKpiValueMobile: { fontSize: 23, marginTop: 3 },
  dailyKpiSubMobile: { fontSize: 11, marginTop: 12 },
  dailyKpiIconMobile: { width: 40, height: 40, borderRadius: 12 },
  appointmentsIconMobile: { backgroundColor: '#E0F7FA' },
  completedIconMobile: { backgroundColor: '#E5F7F0' },
  cancelledIconMobile: { backgroundColor: '#FFF0F2' },
  revenueIconMobile: { backgroundColor: '#F3EDFF' },
  snapshotCardMobile: { width: '100%', padding: 12 },
  snapshotIconMobile: { width: 40, height: 40, borderRadius: 12 },
  labIconMobile: { backgroundColor: '#FFF4DE' },
  medicineIconMobile: { backgroundColor: '#FFF0E6' },
  snapshotValueMobile: { fontSize: 20 },
  snapshotLabelMobile: { fontSize: 12 },
  summaryGridMobile: {
    flexDirection: 'column',
    flexWrap: 'nowrap',
    justifyContent: 'flex-start',
    gap: 4,
  },
  summaryCardMobile: { width: '100%', padding: 14 },
  summaryIconMobile: { width: 36, height: 36 },
  adminSummaryIconMobile: { backgroundColor: '#FFF4DE' },
  inactiveSummaryIconMobile: { backgroundColor: '#FDE8E8' },
  summaryValueMobile: { fontSize: 23 },
  summaryLabelMobile: { fontSize: 13 },

  kpiLabel: { fontSize: 13, fontWeight: '600', color: '#64748B' },
  kpiValue: { fontSize: 20, fontWeight: '800', color: '#0F172A', marginTop: 2 },
  kpiSub: { fontSize: 11, color: '#94A3B8', marginTop: 2 },

  kpiIconBox: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },

  kpiCardSnapshot: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    backgroundColor: '#F8FAFC',
  },
  snapshotValue: { fontSize: 18, fontWeight: '800', color: '#0F172A' },
  snapshotLabel: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 1,
    fontWeight: '600',
  },

  // Middle Metric Grid 4
  metricGrid4: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  metricCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  metricIconBox: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricValue: { fontSize: 18, fontWeight: '800', color: '#0F172A' },
  metricLabel: { fontSize: 12, color: '#64748B', fontWeight: '600' },

  // Search and Filter Bar
  searchFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  clinicFiltersMobile: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 12,
    backgroundColor: '#FFFFFF',
    marginBottom: 14,
    gap: 8,
  },
  statusFilterMobile: { width: '100%' },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 42,
  },
  filterFieldFocused: { borderColor: '#14B8A6', borderWidth: 1.5 },
  searchInput: { flex: 1, fontSize: 13, color: '#0F172A' },

  statusTriggerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 14,
    height: 42,
    minWidth: 120,
  },
  statusTriggerBtnMobile: { width: '100%' },
  statusTriggerBtnText: { fontSize: 13, color: '#334155', fontWeight: '600' },
  statusDropdownMenu: {
    position: 'absolute',
    top: 46,
    right: 0,
    minWidth: 140,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingVertical: 4,
    elevation: 6,
    zIndex: 99,
  },
  statusDropdownItem: { paddingHorizontal: 12, paddingVertical: 8 },
  statusDropdownItemText: { fontSize: 13, color: '#334155' },

  // Table Card
  tableCardContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    marginBottom: 20,
  },
  tableHeaderBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  tableTitleText: { fontSize: 16, fontWeight: '700', color: '#0F172A' },
  tableTitleMobile: { fontSize: 14, fontWeight: '500' },
  columnsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#FFFFFF',
  },
  columnsBtnMobile: {
    width: 40,
    height: 36,
    paddingHorizontal: 0,
    paddingVertical: 0,
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
  },
  columnsBtnText: { fontSize: 12, fontWeight: '600', color: '#334155' },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0D9488',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 8,
  },
  addBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 12 },

  // Table Structure
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  thCell: { fontSize: 12, fontWeight: '700', color: '#64748B' },

  tableBodyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },

  clinicLogoSquare: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#CCFBF1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  clinicTitleText: { fontSize: 13, fontWeight: '700', color: '#0F172A' },
  codeText: { fontSize: 11, color: '#64748B', marginTop: 1 },
  tdText: { fontSize: 12, color: '#334155' },

  statusPillBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  statusActiveBg: { backgroundColor: '#DCFCE7' },
  statusInactiveBg: { backgroundColor: '#FEE2E2' },
  statusPillText: { fontSize: 11, fontWeight: '700' },
  statusActiveText: { color: '#166534' },
  statusInactiveText: { color: '#991B1B' },

  // Mobile Cards
  mobileClinicCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    padding: 12,
  },
  mobileMetaRow: {
    gap: 4,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  mobileMetaItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  metaText: { fontSize: 12, color: '#475569' },

  // Modal
  modalBg: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    maxWidth: 440,
    alignSelf: 'center',
    width: '100%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modalTitle: { fontSize: 18, fontWeight: '700', color: '#0F172A' },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: '#334155',
    marginTop: 10,
    marginBottom: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: '#0F172A',
  },
  modalBtnRow: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    justifyContent: 'flex-end',
  },
  cancelBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
  },
  cancelText: { color: '#475569', fontWeight: '600', fontSize: 13 },
  saveBtn: {
    backgroundColor: '#0D9488',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
  },
  saveText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },

  // Action Popover Menu (Screenshot 2 Match)
  actionPopoverMenu: {
    position: 'absolute',
    top: 32,
    right: 0,
    width: 175,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingVertical: 6,
    paddingHorizontal: 4,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    zIndex: 999,
  },
  actionMenuOverlay: { flex: 1 },
  actionMenuBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.08)',
  },
  actionPopoverPortal: {
    top: 0,
    right: undefined,
    maxHeight: 240,
  },
  popoverItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
  },
  popoverItemText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#334155',
  },

  // View Clinic Modal Styles (Screenshot 3 Match)
  viewClinicCard: {
    width: '100%',
    maxWidth: 620,
    maxHeight: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 10,
    alignSelf: 'center',
  },
  viewClinicHeader: {
    backgroundColor: '#ECFDF5',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#A7F3D0',
  },
  clinicLogoSquareLarge: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CCFBF1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewClinicTitle: { fontSize: 18, fontWeight: '700', color: '#0F172A' },
  viewClinicSubtitle: { fontSize: 12, color: '#64748B', marginTop: 2 },
  viewClinicStatusTag: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  viewClinicStatusText: { fontSize: 11, fontWeight: '700', color: '#166534' },

  viewSectionCard: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 14,
  },
  availabilityBgCard: {
    backgroundColor: '#F0FDFA',
    borderColor: '#CCFBF1',
  },
  sectionHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  viewSectionCardTitle: { fontSize: 14, fontWeight: '700', color: '#0F172A' },
  grid2ColRow: { flexDirection: 'row', gap: 16 },
  grid3ColRow: { flexDirection: 'row', gap: 12 },
  infoBoxLabel: { fontSize: 11, color: '#64748B', fontWeight: '500' },
  infoBoxVal: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
    marginTop: 3,
  },

  viewClinicFooter: {
    padding: 14,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    alignItems: 'flex-end',
    backgroundColor: '#FFFFFF',
  },
  viewClinicCloseBtn: {
    backgroundColor: '#0D9488',
    paddingHorizontal: 22,
    paddingVertical: 9,
    borderRadius: 8,
  },
  viewClinicCloseBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },

  // View Admins Modal Styles (Screenshot 4 Match)
  viewAdminsCard: {
    width: '100%',
    maxWidth: 680,
    maxHeight: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 10,
    alignSelf: 'center',
  },
  viewAdminsHeader: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  tealIconBoxSquare: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: '#0D9488',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewAdminsTitle: { fontSize: 18, fontWeight: '700', color: '#0F172A' },
  viewAdminsSubtitle: { fontSize: 12, color: '#64748B', marginTop: 2 },
  viewAdminsSubHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  addNewAdminBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0D9488',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  addNewAdminBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },

  adminsTableContainer: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    overflow: 'hidden',
  },
  adminsTableHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  adminsTh: { fontSize: 12, fontWeight: '600', color: '#64748B' },
  adminsTableBodyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  adminAvatarCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#E6F4F1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  adminNameText: { fontSize: 13, fontWeight: '600', color: '#0F172A' },
  adminTdText: { fontSize: 12, color: '#475569' },
  adminStatusPill: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  adminStatusText: { fontSize: 11, fontWeight: '700' },

  // Add Admin Modal Styles (Screenshot 5 Match)
  addAdminCard: {
    width: '100%',
    maxWidth: 540,
    maxHeight: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 10,
    alignSelf: 'center',
  },
  addAdminHeader: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  userPlusIconBox: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: '#E6F4F1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addAdminTitle: { fontSize: 18, fontWeight: '700', color: '#0F172A' },
  addAdminSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
    lineHeight: 16,
  },
  formGroupHeader: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 12,
  },
  formLabelText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#334155',
    marginTop: 10,
    marginBottom: 4,
  },
  formInputBox: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 13,
    color: '#0F172A',
    backgroundColor: '#F8FAFC',
  },
  formInputFocused: {
    borderColor: '#0D9488',
    borderWidth: 1.5,
    backgroundColor: '#FFFFFF',
  },

  assignedClinicCard: {
    backgroundColor: '#F0FDFA',
    borderWidth: 1,
    borderColor: '#CCFBF1',
    borderRadius: 10,
    padding: 12,
    marginTop: 14,
    marginBottom: 6,
  },
  assignedClinicHeaderLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
  },
  assignedClinicName: { fontSize: 13, fontWeight: '700', color: '#0F172A' },
  assignedClinicAddress: { fontSize: 12, color: '#64748B' },

  addAdminFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
    padding: 14,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
  },
  addAdminCancelBtn: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderRadius: 8,
  },
  addAdminCancelText: { fontSize: 13, fontWeight: '600', color: '#334155' },
  addAdminSubmitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0D9488',
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderRadius: 8,
  },
  addAdminSubmitText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },

  // Edit / Add Clinic Modal Specific Styles
  editClinicModalCard: {
    width: '100%',
    maxWidth: 640,
    maxHeight: '92%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 10,
    alignSelf: 'center',
  },
  clinicLogoUploadBox: {
    alignSelf: 'center',
    width: 220,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginVertical: 12,
  },
  cameraIconCircleBadge: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    backgroundColor: '#FFFFFF',
  },
  smallCloseBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#F1F5F9',
    borderRadius: 10,
    padding: 2,
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  formDropdownSelectTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: '#F8FAFC',
  },
  formDropdownText: {
    fontSize: 13,
    color: '#0F172A',
  },
  formDropdownList: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    marginTop: 4,
    maxHeight: 150,
    elevation: 3,
    zIndex: 99,
  },
  formDropdownListItem: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  formDropdownItemText: {
    fontSize: 13,
    color: '#334155',
  },
  formInputBoxWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: '#F8FAFC',
  },
  formInputBoxBare: {
    flex: 1,
    paddingVertical: 8,
    fontSize: 13,
    color: '#0F172A',
  },
  editClinicModalHeader: {
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
  },
  editHeaderIconBox: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editClinicModalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
  },
  editClinicModalSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  logoBoxLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#334155',
    marginBottom: 8,
  },
  emptyClinicsState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 36,
    paddingHorizontal: 16,
    gap: 10,
  },
  emptyClinicsText: { fontSize: 13, color: '#64748B', textAlign: 'center' },
  clearClinicFiltersText: { fontSize: 13, color: '#0D9488', fontWeight: '600' },
  changeLogoLink: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0D9488',
  },
  logoHelperText: {
    fontSize: 11,
    color: '#94A3B8',
    marginTop: 4,
  },
  apiTimeHelperText: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 4,
  },
  mobileAdminCardItem: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },

  // Active Status in Edit Admin Modal
  adminStatusCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 14,
    backgroundColor: '#FFFFFF',
  },
  adminStatusCardTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0F172A',
  },
  adminStatusCardSubtitle: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
  },
  adminStatusDropdownBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    minWidth: 96,
  },
  adminStatusDropdownText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#0F172A',
  },
  adminStatusDropdownMenu: {
    position: 'absolute',
    top: 36,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    elevation: 6,
    zIndex: 999,
    minWidth: 110,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  adminStatusDropdownOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  adminStatusDropdownOptionSelected: {
    backgroundColor: '#F0FDFA',
  },
  adminStatusOptionText: {
    fontSize: 13,
    color: '#334155',
  },
  adminStatusOptionTextActive: {
    color: '#0D9488',
    fontWeight: '600',
  },

  // Reset Password Card in Edit Admin Modal
  adminResetPasswordCard: {
    backgroundColor: '#F0FDFA',
    borderWidth: 1,
    borderColor: '#CCFBF1',
    borderRadius: 12,
    padding: 14,
    marginTop: 14,
  },
  adminResetPasswordTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0F172A',
  },
  adminResetPasswordSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 3,
    marginBottom: 12,
  },
  adminResetPasswordBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#99F6E4',
    borderRadius: 8,
    paddingVertical: 9,
    paddingHorizontal: 14,
  },
  adminResetPasswordBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0D9488',
  },

  // Password Input Field with Eye Icon
  passwordInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 10,
    marginTop: 4,
  },
  passwordInputField: {
    flex: 1,
    paddingVertical: 9,
    fontSize: 13,
    color: '#0F172A',
  },
  passwordEyeBtn: {
    padding: 6,
  },
  invalidInputBox: {
    borderColor: '#EF4444',
    borderWidth: 1.5,
  },
  fieldErrorText: {
    fontSize: 12,
    color: '#EF4444',
    marginTop: 4,
    fontWeight: '500',
  },

  extractedInline1: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  extractedInline2: { marginLeft: 12 },
  extractedInline3: { marginTop: 8 },
  extractedInline4: { flex: 1, minWidth: 200, zIndex: 30 },
  extractedInline5: { flex: 1.5, minWidth: 240, zIndex: 40 },
  extractedInline6: { alignItems: 'flex-start', marginTop: 10 },
  extractedInline7: { marginRight: 6 },
  extractedInline8: { fontSize: 11 },
  extractedInline9: { fontSize: 17 },
  extractedInline10: { fontSize: 10 },
  extractedInline11: { width: 32, height: 32 },
  extractedInline12: { backgroundColor: '#E6F4F1' },
  extractedInline13: { backgroundColor: '#DCFCE7' },
  extractedInline14: { backgroundColor: '#FEE2E2' },
  extractedInline15: { backgroundColor: '#F3E8FF' },
  extractedInline16: { marginTop: 18 },
  extractedInline17: { fontSize: 16 },
  extractedInline18: { backgroundColor: '#FFEDD5' },
  extractedInline19: { backgroundColor: '#CCFBF1' },
  extractedInline20: { flexDirection: 'column', alignItems: 'stretch' },
  extractedInline21: { marginRight: 8 },
  extractedInline22: { position: 'relative', zIndex: 20 },
  extractedInline23: { flexDirection: 'row', alignItems: 'center' },
  extractedInline24: { flexDirection: 'row', gap: 8 },
  extractedInline25: { marginRight: 4 },
  extractedInline26: { padding: 12, gap: 10 },
  extractedInline27: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  extractedInline28: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  extractedInline29: { flex: 1, marginLeft: 10 },
  extractedInline30: { flex: 1 },
  extractedInline31: { padding: 6, marginLeft: 4 },
  extractedInline32: {
    position: 'relative',
    top: 0,
    right: 0,
    width: '100%',
    marginBottom: 8,
  },
  extractedInline33: { borderTopWidth: 1, borderTopColor: '#F1F5F9' },
  extractedInline34: { width: 220 },
  extractedInline35: { width: 200 },
  extractedInline36: { width: 130 },
  extractedInline37: { width: 110 },
  extractedInline38: { width: 160 },
  extractedInline39: { width: 150 },
  extractedInline40: { width: 120 },
  extractedInline41: { width: 90, textAlign: 'center' },
  extractedInline42: { width: 140, textAlign: 'center' },
  extractedInline43: { width: 80, textAlign: 'right' },
  extractedInline44: {
    width: 220,
    flexDirection: 'row',
    alignItems: 'center',
  },
  extractedInline45: {
    width: 200,
    flexDirection: 'row',
    alignItems: 'center',
  },
  extractedInline46: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  extractedInline47: { width: 130, justifyContent: 'center' },
  extractedInline48: { width: 110, justifyContent: 'center' },
  extractedInline49: { width: 160, justifyContent: 'center' },
  extractedInline50: { width: 150, justifyContent: 'center' },
  extractedInline51: { width: 120, justifyContent: 'center' },
  extractedInline52: {
    width: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  extractedInline53: {
    width: 140,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  extractedInline54: {
    width: 80,
    alignItems: 'flex-end',
    justifyContent: 'center',
    zIndex: 50,
  },
  extractedInline55: { padding: 6 },
  extractedInline56: {
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    marginTop: 2,
  },
  extractedInline57: { width: '96%', maxHeight: '92%' },
  extractedInline58: { padding: 18 },
  addAdminFormScroll: { flex: 1, flexShrink: 1, minHeight: 0 },
  addAdminFormContent: { paddingBottom: 24 },
  extractedInline59: {
    width: '100%',
    height: '100%',
    borderRadius: 100,
  },
  extractedInline60: { marginTop: 4 },
  extractedInline61: { flexDirection: 'column', gap: 0 },
  extractedInline62: { color: '#EF4444' },
  extractedInline63: { marginTop: 10 },
  extractedInline64: {
    flexDirection: 'column',
    gap: 0,
    marginTop: 0,
  },
  extractedInline65: { flex: 1, marginLeft: 12 },
  extractedInline66: { padding: 4 },
  extractedInline67: { padding: 16 },
  extractedInline68: { flexDirection: 'column', gap: 10 },
  extractedInline69: { marginTop: 12 },
  extractedInline70: {
    flexDirection: 'column',
    gap: 10,
    marginTop: 10,
  },
  extractedInline71: { marginTop: 14 },
  extractedInline72: { marginTop: 14, marginBottom: 10 },
  extractedInline73: { color: '#0D9488' },
  extractedInline74: { paddingHorizontal: 16, paddingBottom: 16 },
  extractedInline75: {
    paddingVertical: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  extractedInline76: { marginTop: 8, fontSize: 12, color: '#64748B' },
  extractedInline77: {
    paddingVertical: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    marginVertical: 8,
  },
  extractedInline78: {
    marginTop: 8,
    fontSize: 13,
    color: '#64748B',
    fontWeight: '500',
  },
  extractedInline79: { gap: 10 },
  extractedInline80: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  extractedInline81: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  extractedInline82: { marginTop: 8, gap: 4 },
  extractedInline83: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  extractedInline84: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  extractedInline85: { marginRight: 5 },
  extractedInline86: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0F172A',
  },
  extractedInline87: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#FEE2E2',
    backgroundColor: '#FEF2F2',
  },
  extractedInline88: {
    fontSize: 12,
    fontWeight: '600',
    color: '#DC2626',
  },
  extractedInline89: { flex: 2.2 },
  extractedInline90: { flex: 2.5 },
  extractedInline91: { flex: 1.8 },
  extractedInline92: { flex: 1.2, textAlign: 'center' },
  extractedInline93: { flex: 1.4, textAlign: 'right' },
  extractedInline94: {
    flex: 2.2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  extractedInline95: { flex: 1.2, alignItems: 'center' },
  extractedInline96: {
    flex: 1.4,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  extractedInline97: { height: 60, textAlignVertical: 'top' },
  extractedInline98: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  extractedInline99: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
  },
  extractedInline100: { backgroundColor: '#F1F5F9', color: '#64748B' },
  extractedInline101: { flex: 1, marginRight: 8 },
  extractedInline102: { position: 'relative' },
  extractedInline103: { marginLeft: 6 },
  statsValueCell: { flex: 1 },
  statsValueCellMobile: { paddingRight: 4 },
  detailsValueCell: { flex: 1 },
  detailsValueCellMobile: { marginLeft: 6 },
  activeActionText: { color: '#DC2626' },
  inactiveActionText: { color: '#16A34A' },
});
