import { StyleSheet } from 'react-native';

export const inventoryStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F8FAFC' },
  content: { padding: 13, paddingBottom: 44, gap: 11 },
  heading: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 2 },
  headingIcon: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: '#CCFBF1' },
  headingText: { flex: 1, minWidth: 0 },
  title: { color: '#0F172A', fontSize: 18, fontWeight: '800' },
  subtitle: { color: '#64748B', fontSize: 11, lineHeight: 16, marginTop: 2 },
  clinicSelect: { minHeight: 39, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: '#BFECE4', borderRadius: 11, backgroundColor: '#F7FCFB' },
  clinicSelectText: { flex: 1, color: '#334155', fontSize: 12 },
  clinicOptions: { marginTop: -5, padding: 5, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 11, backgroundColor: '#fff' },
  clinicOption: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10, borderRadius: 8 },
  clinicOptionActive: { backgroundColor: '#F0FDFA' },
  clinicOptionText: { color: '#334155', fontSize: 12 },
  refreshButton: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 11, backgroundColor: '#F8FAFC' },
  refreshText: { color: '#0F172A', fontSize: 12, fontWeight: '600' },
  refreshed: { color: '#71839D', fontSize: 10, marginTop: -6 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  statCard: { flexGrow: 1, flexBasis: '47%', minHeight: 76, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 13, paddingVertical: 10, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 13, backgroundColor: '#fff' },
  statLabel: { color: '#64748B', fontSize: 11 },
  statValue: { marginTop: 3, color: '#0F172A', fontSize: 20, fontWeight: '800' },
  statIcon: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 17, backgroundColor: '#F0FDFA' },
  panel: { overflow: 'hidden', borderWidth: 1.5, borderColor: '#38D5C3', borderRadius: 13, backgroundColor: '#fff' },
  panelHead: { paddingHorizontal: 14, paddingTop: 14, paddingBottom: 2, gap: 5, backgroundColor: '#fff' },
  panelTitle: { color: '#0F172A', fontSize: 17, fontWeight: '800' },
  panelSub: { color: '#64748B', fontSize: 11, lineHeight: 16, marginTop: 2 },
  toolbar: { flexDirection: 'column', gap: 8, padding: 11 },
  primaryButton: { minHeight: 42, flexGrow: 1, flexBasis: '45%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 9, borderRadius: 10, backgroundColor: '#22A699' },
  primaryButtonText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  primaryButtonFull: { alignSelf: 'stretch', minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderRadius: 10, backgroundColor: '#22A699' },
  secondaryButtonFull: { alignSelf: 'stretch', minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 10, backgroundColor: '#fff' },
  columnsButton: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 9, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 10, backgroundColor: '#F8FAFC' },
  panelControl: { marginHorizontal: 14, marginTop: 8 },
  secondaryButton: { minHeight: 42, flexGrow: 1, flexBasis: '45%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 9, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 10, backgroundColor: '#fff' },
  secondaryButtonText: { color: '#334155', fontSize: 11, fontWeight: '700' },
  searchBox: { minHeight: 45, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 11, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 11, backgroundColor: '#fff' },
  searchInput: { flex: 1, minWidth: 0, minHeight: 42, paddingVertical: 7, color: '#0F172A', fontSize: 13 },
  listMeta: { paddingHorizontal: 13, paddingTop: 10, color: '#64748B', fontSize: 11 },
  cardList: { padding: 10, gap: 9 },
  card: { padding: 13, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 13, backgroundColor: '#fff' },
  cardTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  cardName: { color: '#0F172A', fontSize: 14, fontWeight: '700', flexShrink: 1 },
  cardCode: { color: '#64748B', fontSize: 10, marginTop: 3 },
  badge: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: 14, backgroundColor: '#DCFCE7' },
  badgeActive: { backgroundColor: '#22A699' },
  badgeActiveText: { color: '#fff' },
  badgeMuted: { backgroundColor: '#F1F5F9' },
  badgeText: { color: '#15803D', fontSize: 10, fontWeight: '700' },
  badgeMutedText: { color: '#64748B', fontSize: 10, fontWeight: '700' },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  detailCell: { flexGrow: 1, flexBasis: '45%', padding: 9, borderRadius: 9, backgroundColor: '#F8FAFC' },
  detailLabel: { color: '#64748B', fontSize: 9 },
  detailValue: { color: '#0F172A', fontSize: 12, fontWeight: '700', marginTop: 3 },
  homeCollectionBadge: { alignSelf: 'flex-start', marginTop: 9, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 14, backgroundColor: '#22A699' },
  homeCollectionText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  description: { color: '#64748B', fontSize: 11, lineHeight: 16, marginTop: 10 },
  editButton: { minHeight: 38, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, marginTop: 12, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 9, backgroundColor: '#F8FAFC' },
  editText: { color: '#334155', fontSize: 11, fontWeight: '700', textTransform: 'capitalize' },
  empty: { alignItems: 'center', paddingHorizontal: 22, paddingVertical: 27 },
  emptyTitle: { color: '#334155', fontSize: 13, fontWeight: '700', textAlign: 'center', marginTop: 8 },
  emptyText: { color: '#71839D', fontSize: 11, textAlign: 'center', marginTop: 4 },
  errorBox: { padding: 12, borderWidth: 1, borderColor: '#FECACA', borderRadius: 11, backgroundColor: '#FEF2F2' },
  errorText: { color: '#B91C1C', fontSize: 12 },
  retry: { color: '#0F766E', fontSize: 12, fontWeight: '700', marginTop: 8 },
  modalBackdrop: { flex: 1, justifyContent: 'center', padding: 13, backgroundColor: 'rgba(15,23,42,0.54)' },
  modalCard: { maxHeight: '92%', overflow: 'hidden', borderRadius: 17, backgroundColor: '#fff' },
  masterModalBackdrop: { flex: 1, justifyContent: 'center', paddingHorizontal: 24, paddingVertical: 16, backgroundColor: 'rgba(15,23,42,0.72)' },
  masterModalCard: { height: '92%', maxHeight: '96%', flexShrink: 1, overflow: 'hidden', borderRadius: 17, backgroundColor: '#F8FAFC' },
  modalHeader: { padding: 16, borderBottomWidth: 1, borderBottomColor: '#E2E8F0', backgroundColor: '#F0FDFA' },
  masterModalHeader: { paddingHorizontal: 14, paddingTop: 14, paddingBottom: 13, borderBottomWidth: 1, borderBottomColor: '#E2E8F0', backgroundColor: '#F0FDFA' },
  masterHeaderTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  masterHeaderIcon: { width: 38, height: 38, flexShrink: 0, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: '#0D9488' },
  masterHeaderText: { flex: 1, minWidth: 0, alignItems: 'flex-start', paddingTop: 1 },
  masterModalTitle: { color: '#0F172A', fontSize: 17, fontWeight: '700', textAlign: 'left' },
  masterModalSubtitle: { color: '#475569', fontSize: 12, lineHeight: 17, marginTop: 4, textAlign: 'left' },
  closeIconButton: { width: 28, height: 28, flexShrink: 0, alignItems: 'center', justifyContent: 'center', marginTop: -5, marginRight: -5 },
  customCloseIcon: { position: 'absolute', top: 7, right: 9, width: 28, height: 28, alignItems: 'center', justifyContent: 'center', zIndex: 1 },
  createCustomButton: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, marginTop: 13, borderWidth: 1, borderColor: '#99F6E4', borderRadius: 10, backgroundColor: '#fff' },
  createCustomText: { color: '#0F766E', fontSize: 12, fontWeight: '700' },
  importMasterButton: { minHeight: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, marginTop: 4 },
  importMasterText: { color: '#0F766E', fontSize: 10, fontWeight: '700' },
  customModalHeader: { alignItems: 'center', paddingHorizontal: 22, paddingTop: 17, paddingBottom: 13, borderBottomWidth: 1, borderBottomColor: '#E2E8F0', backgroundColor: '#F0FDFA' },
  customModalTitle: { color: '#0F172A', fontSize: 16, fontWeight: '800', textAlign: 'center' },
  customModalSubtitle: { color: '#64748B', fontSize: 11, lineHeight: 16, marginTop: 5, textAlign: 'center' },
  modalHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  modalHeaderButtons: { flexDirection: 'row', gap: 7, marginTop: 9 },
  modalHeaderButton: { minHeight: 38, flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingHorizontal: 5, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 9, backgroundColor: '#fff' },
  modalTitle: { color: '#0F172A', fontSize: 18, fontWeight: '800' },
  modalSubtitle: { color: '#64748B', fontSize: 11, lineHeight: 16, marginTop: 4 },
  modalBody: { padding: 14, gap: 10 },
  modalActions: { flexDirection: 'row', gap: 8, padding: 13, borderTopWidth: 1, borderTopColor: '#E2E8F0' },
  masterModalFooter: { padding: 11, borderTopWidth: 1, borderTopColor: '#E2E8F0', backgroundColor: '#fff' },
  masterModalScroll: { flex: 1, minHeight: 0 },
  masterModalScrollContent: { paddingBottom: 12 },
  mappingModalBackdrop: { flex: 1, justifyContent: 'center', paddingHorizontal: 20, paddingVertical: 18, backgroundColor: 'rgba(15,23,42,0.68)' },
  mappingModalCard: { height: '84%', maxHeight: '90%', flexShrink: 1, overflow: 'hidden', borderRadius: 17, backgroundColor: '#F8FAFC' },
  mappingModalHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingHorizontal: 15, paddingTop: 15, paddingBottom: 13, borderBottomWidth: 1, borderBottomColor: '#E2E8F0', backgroundColor: '#F0FDFA' },
  mappingHeaderText: { flex: 1, minWidth: 0, alignItems: 'center', paddingTop: 1 },
  mappingModalTitle: { color: '#0F172A', fontSize: 16, fontWeight: '700', textAlign: 'center' },
  mappingModalSubtitle: { color: '#475569', fontSize: 11, lineHeight: 16, marginTop: 4, textAlign: 'center' },
  mappingModalScroll: { flex: 1, minHeight: 0 },
  mappingModalBody: { padding: 15, gap: 15 },
  mappingTestCard: { padding: 14, borderWidth: 1, borderColor: '#99F6E4', borderRadius: 15, backgroundColor: '#fff' },
  mappingModalFooter: { flexDirection: 'row', gap: 8, paddingHorizontal: 11, paddingVertical: 10, paddingBottom: 12, borderTopWidth: 1, borderTopColor: '#E2E8F0', backgroundColor: '#fff' },
  mappingCancelButton: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 10, backgroundColor: '#F8FAFC' },
  mappingSaveButton: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#22A699', borderRadius: 10, backgroundColor: '#22A699' },
  masterFooterClose: { minHeight: 40, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 10, backgroundColor: '#F8FAFC' },
  modalAction: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 10, backgroundColor: '#fff' },
  modalActionPrimary: { borderColor: '#22A699', backgroundColor: '#22A699' },
  modalActionText: { color: '#334155', fontSize: 12, fontWeight: '700' },
  modalActionPrimaryText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  inputLabel: { color: '#334155', fontSize: 11, fontWeight: '700', marginTop: 2 },
  requiredMark: { color: '#EF4444' },
  formField: { gap: 7 },
  choiceField: { gap: 7 },
  choiceButton: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 11, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 10, backgroundColor: '#F8FAFC' },
  choiceOptions: { marginTop: 5, padding: 4, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 10, backgroundColor: '#fff' },
  choiceOption: { minHeight: 38, justifyContent: 'center', paddingHorizontal: 10, borderRadius: 7 },
  choiceOptionActive: { backgroundColor: '#F0FDFA' },
  choiceText: { color: '#334155', fontSize: 12 },
  input: { minHeight: 43, paddingHorizontal: 11, paddingVertical: 9, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 10, color: '#0F172A', backgroundColor: '#fff', fontSize: 13 },
  textArea: { minHeight: 76, textAlignVertical: 'top' },
  inputRow: { flexDirection: 'row', gap: 8 },
  inputHalf: { flex: 1 },
  toggleRow: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingHorizontal: 11, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, backgroundColor: '#fff' },
  toggleLabel: { color: '#334155', fontSize: 12, fontWeight: '600', flex: 1 },
  toggleValue: { color: '#0F766E', fontSize: 11, fontWeight: '700' },
  toggleValueMuted: { color: '#64748B' },
  flexFillMinWidth: { flex: 1, minWidth: 0 },
  flexFill: { flex: 1 },
  fieldInset: { paddingHorizontal: 11, paddingTop: 11 },
  errorInset: { margin: 11 },
  loadingInset: { padding: 22 },
  badgeRow: { flexDirection: 'row', gap: 7, marginTop: 8 },
  masterSearchInset: { paddingHorizontal: 12, paddingTop: 11 },
  masterControls: { gap: 8, marginHorizontal: 11, marginTop: 11, padding: 10, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 13, backgroundColor: '#fff' },
  masterSearchBox: { minHeight: 41, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 10, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, backgroundColor: '#F8FAFC' },
  filterSelect: { minHeight: 41, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 11, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, backgroundColor: '#F8FAFC' },
  filterSelectText: { color: '#334155', fontSize: 11 },
  filterOptions: { padding: 4, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, backgroundColor: '#fff' },
  filterOption: { minHeight: 35, justifyContent: 'center', paddingHorizontal: 9, borderRadius: 7 },
  filterOptionActive: { backgroundColor: '#F0FDFA' },
  filterOptionText: { color: '#334155', fontSize: 11 },
  masterRefreshButton: { minHeight: 41, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, backgroundColor: '#F8FAFC' },
  masterRefreshTime: { color: '#71839D', fontSize: 9, marginTop: -4 },
  masterSummary: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 7, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#E2E8F0' },
  masterCount: { color: '#475569', fontSize: 11 },
  masterCountStrong: { color: '#0F172A', fontWeight: '800' },
  masterSummaryBadges: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 },
  masterCardList: { paddingHorizontal: 11, paddingTop: 11, gap: 9 },
  masterBadges: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  masterCardMapped: { borderColor: '#99F6E4', backgroundColor: '#F4FCFA' },
  badgeOutline: { borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#fff' },
  badgeOutlineText: { color: '#334155', fontSize: 10, fontWeight: '600' },
  badgeTeal: { backgroundColor: '#CCFBF1' },
  badgeTealText: { color: '#0F766E', fontSize: 10, fontWeight: '700' },
  masterActionReady: { borderColor: '#22A699', backgroundColor: '#22A699' },
  masterActionMapped: { borderColor: '#DCE5E9', backgroundColor: '#F8FAFC' },
  masterActionReadyText: { color: '#fff' },
  hidden: { display: 'none' },
  masterMetaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 13, paddingTop: 4 },
  masterErrorInset: { paddingHorizontal: 13, paddingTop: 6 },
  masterLoadingInset: { padding: 20 },
  filterRow: { flexDirection: 'row', gap: 7, paddingHorizontal: 13, paddingVertical: 10 },
  filterChip: { flex: 1, minHeight: 36, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 18, backgroundColor: '#fff' },
  filterChipActive: { borderColor: '#0D9488', backgroundColor: '#0D9488' },
  filterText: { color: '#64748B', fontSize: 10, fontWeight: '700' },
  filterTextActive: { color: '#fff' },
  masterCard: { padding: 12, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, backgroundColor: '#fff' },
  masterAction: { minHeight: 38, alignItems: 'center', justifyContent: 'center', marginTop: 10, borderWidth: 1, borderColor: '#BFE3DB', borderRadius: 9, backgroundColor: '#F0FDFA' },
  masterActionText: { color: '#0F766E', fontSize: 11, fontWeight: '700' },
  fileBox: { padding: 12, borderWidth: 1, borderStyle: 'dashed', borderColor: '#99DCD0', borderRadius: 11, backgroundColor: '#F8FFFD' },
  fileName: { color: '#334155', fontSize: 12, fontWeight: '600', marginTop: 7 },
});
