import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  content: { padding: 13, paddingBottom: 48, gap: 11 },
  flex: { flex: 1, minWidth: 0 },
  pageHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 3,
  },
  headingIcon: {
    width: 48,
    height: 48,
    borderRadius: 13,
    backgroundColor: '#CCFBF1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageTitle: { color: '#0F172A', fontSize: 22, fontWeight: '800' },
  pageSubtitle: {
    color: '#64748B',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  refreshButton: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 11, backgroundColor: '#F8FAFC' },
  refreshButtonText: { color: '#0F172A', fontSize: 12, fontWeight: '600' },
  lastRefreshedText: { color: '#71839D', fontSize: 9, marginTop: -6, marginBottom: 1 },
  refreshIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#DCE5E9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  clinicSelector: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#BFE3DB',
    borderRadius: 13,
  },
  clinicLabel: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  clinicName: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 2,
  },
  searchBox: {
    minHeight: 47,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    backgroundColor: '#fff',
  },
  searchPanel: { padding: 12, gap: 9, borderWidth: 1, borderColor: '#C7F1E9', borderRadius: 13, backgroundColor: '#F8FFFD' },
  searchButton: { minHeight: 41, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#22A699' },
  searchButtonText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  clinicDataNote: { flexDirection: 'row', alignItems: 'center', minWidth: 0, paddingTop: 1 },
  onlineDot: { width: 8, height: 8, marginRight: 7, borderRadius: 4, backgroundColor: '#10B981' },
  clinicDataText: { color: '#71839D', fontSize: 10 },
  clinicDataName: { flexShrink: 1, color: '#0F172A', fontSize: 10, fontWeight: '700' },
  searchInput: {
    flex: 1,
    minHeight: 44,
    color: '#0F172A',
    fontSize: 13,
    paddingVertical: 8,
  },
  labResultsPanel: { width: '100%', overflow: 'hidden', borderWidth: 1, borderColor: '#9AE6D9', borderRadius: 15, backgroundColor: '#fff' },
  labSummary: { padding: 14, gap: 12, backgroundColor: '#F4F8FF' },
  summaryHeading: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  summaryIcon: { width: 44, height: 44, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0D9488' },
  summaryTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  summaryTitle: { color: '#0F172A', fontSize: 17, fontWeight: '800' },
  summaryCount: { minWidth: 25, height: 25, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6, borderRadius: 13, backgroundColor: '#0F172A' },
  summaryCountText: { color: '#fff', fontSize: 11, fontWeight: '800' },
  summarySubtitle: { color: '#64748B', fontSize: 12, lineHeight: 17, marginTop: 3 },
  statsRow: { flexDirection: 'row', gap: 0, overflow: 'hidden', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, backgroundColor: '#fff' },
  statCard: {
    flex: 1,
    minHeight: 53,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRightWidth: 1,
    borderRightColor: '#E2E8F0',
    backgroundColor: '#fff',
  },
  statIcon: {
    width: 16,
    height: 20,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  statCopy: { flex: 1, minWidth: 0 },
  statLabel: { color: '#64748B', fontSize: 9, textTransform: 'uppercase' },
  statValue: {
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 0,
  },
  listDivider: { height: 2, width: '100%', flexDirection: 'row', alignSelf: 'center', overflow: 'hidden' },
  dividerTeal: { flex: 1, backgroundColor: '#0F766E' },
  dividerBlue: { flex: 1, backgroundColor: '#2563EB' },
  dividerOrange: { flex: 1, backgroundColor: '#F97316' },
  tabs: { flexDirection: 'row', gap: 6 },
  tabButton: {
    flex: 1,
    minHeight: 40,
    paddingHorizontal: 7,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#DCE5E9',
    backgroundColor: '#fff',
  },
  tabButtonActive: { backgroundColor: '#0D9488', borderColor: '#0D9488' },
  tabText: { color: '#64748B', fontSize: 12, fontWeight: '700' },
  tabTextActive: { color: '#fff' },
  addInventoryButton: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 10,
    backgroundColor: '#0D9488',
  },
  addInventoryText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  inventoryActions: { gap: 8 },
  masterButton: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderWidth: 1,
    borderColor: '#BFE3DB',
    borderRadius: 10,
    backgroundColor: '#F0FDFA',
  },
  masterTestOption: {
    minHeight: 55,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F6',
  },
  inventoryEditButton: { alignSelf: 'flex-start', marginTop: 12 },
  patientCard: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E7EEF2',
    backgroundColor: '#fff',
  },
  patientHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 5,
    paddingBottom: 7,
  },
  patientAvatar: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0F9B8E' },
  patientAvatarText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  patientName: { color: '#0F172A', fontSize: 16, fontWeight: '800' },
  totalPrice: { color: '#0F766E', fontSize: 14, fontWeight: '800' },
  testCard: {
    paddingHorizontal: 2,
    paddingTop: 8,
    paddingBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F6',
  },
  patientDoctorRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingHorizontal: 8, paddingBottom: 7, marginBottom: 8, borderBottomWidth: 1, borderBottomColor: '#EEF2F6' },
  patientDoctor: { flex: 1, color: '#71839D', fontSize: 11 },
  testSummaryBox: { padding: 11, gap: 8, borderLeftWidth: 2, borderLeftColor: '#DCE5E9', borderRadius: 7, backgroundColor: '#F8FAFC' },
  testSummaryActions: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 6 },
  pricePill: { color: '#0F766E', fontSize: 10, paddingHorizontal: 8, paddingVertical: 4, borderWidth: 1, borderColor: '#99F6E4', borderRadius: 12, backgroundColor: '#F0FDFA' },
  pendingBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, backgroundColor: '#FEF3C7' },
  pendingText: { color: '#92400E', fontSize: 10, fontWeight: '600' },
  editReportAction: { minHeight: 26, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 3 },
  reportCheckCircle: { width: 15, height: 15, borderWidth: 1, borderColor: '#14B8A6', borderRadius: 8, backgroundColor: '#fff' },
  editReportText: { color: '#0F172A', fontSize: 11, fontWeight: '600' },
  patientFooter: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingTop: 8 },
  viewButton: { minHeight: 32, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 9, backgroundColor: '#fff' },
  viewButtonText: { color: '#334155', fontSize: 11, fontWeight: '600' },
  readyCountText: { color: '#71839D', fontSize: 10 },
  cardMetaRow: { paddingHorizontal: 8, paddingTop: 6 },
  cardHeading: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  cardTitle: { color: '#0F172A', fontSize: 14, fontWeight: '700' },
  cardMeta: { color: '#71839D', fontSize: 11, marginTop: 4, lineHeight: 16 },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: 1,
    borderRadius: 20,
  },
  statusText: { fontSize: 10, fontWeight: '700', textTransform: 'capitalize' },
  testDetails: { gap: 9, marginTop: 12 },
  detailRow: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  detailLabel: { color: '#71839D', fontSize: 10 },
  detailValue: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  secondaryButton: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#BFE3DB',
    borderRadius: 9,
    backgroundColor: '#F0FDFA',
  },
  secondaryText: { color: '#0F766E', fontSize: 11, fontWeight: '700' },
  reportCard: {
    padding: 14,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#DCE5E9',
    backgroundColor: '#fff',
    elevation: 1,
  },
  patientLabel: {
    color: '#64748B',
    fontSize: 12,
    marginTop: 9,
    marginBottom: 7,
  },
  readyBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: '#DCFCE7',
  },
  readyText: { color: '#047857', fontSize: 10, fontWeight: '700' },
  abnormalBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: '#FEE2E2',
  },
  abnormalText: { color: '#B91C1C', fontSize: 10, fontWeight: '700' },
  resultRow: {
    paddingVertical: 7,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  resultParameter: { color: '#334155', fontSize: 12, fontWeight: '700' },
  resultValue: { color: '#0F172A', fontSize: 13, marginTop: 2 },
  resultReference: { color: '#71839D', fontSize: 11, marginTop: 2 },
  reportRemarks: {
    color: '#475569',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
  },
  downloadButton: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#BFE3DB',
    borderRadius: 9,
  },
  downloadText: { color: '#0F766E', fontSize: 11, fontWeight: '700' },
  errorBox: { padding: 13, borderRadius: 12, backgroundColor: '#FEF2F2' },
  errorText: { color: '#B91C1C', fontSize: 12 },
  retryText: {
    color: '#0F766E',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 7,
  },
  loading: { marginTop: 35 },
  emptyCard: {
    minHeight: 125,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 20,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DCE5E9',
    backgroundColor: '#fff',
  },
  emptyText: { color: '#64748B', fontSize: 13, textAlign: 'center' },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: 16,
    backgroundColor: 'rgba(15,23,42,0.45)',
  },
  modalCard: {
    maxHeight: '82%',
    padding: 18,
    borderRadius: 18,
    backgroundColor: '#fff',
  },
  reportModal: {
    maxHeight: '92%',
    padding: 14,
    borderRadius: 18,
    backgroundColor: '#fff',
    position: 'relative',
    paddingTop: 24,
  },
  reportModalTitle: { textAlign: 'center', marginTop: 3 },
  reportCloseButton: { position: 'absolute', zIndex: 2, top: 12, right: 12, width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  fieldLabel: { color: '#0F172A', fontSize: 12, fontWeight: '500' },
  requiredMark: { color: '#EF4444' },
  formFieldSpacing: { marginTop: 14 },
  selectField: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12, marginTop: 7, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, backgroundColor: '#F8FAFC' },
  selectFieldText: { color: '#0F172A', fontSize: 13 },
  selectOptions: { marginTop: 4, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, backgroundColor: '#fff' },
  selectOption: { minHeight: 38, justifyContent: 'center', paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  addParameterText: { color: '#0F172A', fontSize: 12, fontWeight: '600' },
  deleteParameterButton: { alignSelf: 'flex-start', padding: 4, marginTop: 5 },
  reportFormActions: { alignItems: 'stretch', gap: 7, marginTop: 16, marginBottom: 8 },
  reportSubmitButton: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderRadius: 10, backgroundColor: '#22A699' },
  reportCancelButton: { minHeight: 40, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, backgroundColor: '#fff' },
  patientReportModal: { maxHeight: '92%', overflow: 'hidden', borderRadius: 16, backgroundColor: '#fff' },
  patientReportHeader: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  patientReportIcon: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: '#0D9488' },
  patientReportTitle: { color: '#0F172A', fontSize: 16, fontWeight: '800' },
  patientReportSubtitle: { color: '#64748B', fontSize: 12, marginTop: 3 },
  patientReportBody: { backgroundColor: '#F1F5F9' },
  patientReportContent: { padding: 12 },
  reportPaper: { overflow: 'hidden', borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#fff' },
  reportPaperHeader: { flexDirection: 'row', alignItems: 'center', gap: 9, padding: 14, borderBottomWidth: 2, borderBottomColor: '#0D9488' },
  reportClinicName: { color: '#0F172A', fontSize: 16, fontWeight: '800' },
  reportClinicCaption: { color: '#0F766E', fontSize: 8, fontWeight: '700', marginTop: 3 },
  reportIssued: { maxWidth: 90, color: '#0F766E', fontSize: 9, fontWeight: '700', textAlign: 'right' },
  patientDetailsBlock: { flexDirection: 'row', gap: 12, padding: 14, borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  reportOverline: { color: '#64748B', fontSize: 9, fontWeight: '800', textTransform: 'uppercase' },
  reportPatientName: { color: '#0F172A', fontSize: 15, fontWeight: '800', marginTop: 6 },
  reportDoctor: { color: '#0F172A', fontSize: 12, fontWeight: '600', marginTop: 5 },
  reportMeta: { color: '#64748B', fontSize: 10, lineHeight: 15, marginTop: 4 },
  reportSectionTitle: { color: '#334155', fontSize: 10, fontWeight: '800', textTransform: 'uppercase', paddingHorizontal: 14, paddingTop: 14, paddingBottom: 7 },
  reportTableFrame: { marginHorizontal: 10, borderWidth: 1, borderColor: '#E2E8F0', overflow: 'hidden' },
  reportTableHeader: { flexDirection: 'row', backgroundColor: '#020617' },
  reportTableHeadCell: { minHeight: 38, color: '#fff', fontSize: 10, fontWeight: '700', paddingHorizontal: 7, paddingVertical: 10, borderRightWidth: 1, borderRightColor: '#334155' },
  reportColTest: { width: 132 },
  reportColParameter: { width: 105 },
  reportColResult: { width: 85 },
  reportColUnit: { width: 65 },
  reportColReference: { width: 105 },
  reportColStatus: { width: 88 },
  reportColPrice: { width: 82 },
  reportTableRow: { flexDirection: 'row', minHeight: 38, borderBottomWidth: 1, borderBottomColor: '#E2E8F0', backgroundColor: '#fff' },
  reportTableCell: { color: '#334155', fontSize: 10, paddingHorizontal: 7, paddingVertical: 9, borderRightWidth: 1, borderRightColor: '#E2E8F0' },
  reportTableTest: { color: '#0F172A', fontWeight: '700' },
  reportTableResult: { color: '#0F172A', fontWeight: '700' },
  reportTablePrice: { color: '#0F172A', fontWeight: '700', textAlign: 'right' },
  reportTableTotal: { backgroundColor: '#F0FDFA' },
  reportTableTotalLabel: { color: '#0F172A', fontWeight: '800', textAlign: 'right' },
  reportTableTotalLabelWidth: { width: 580 },
  reportResultCard: { padding: 11, marginHorizontal: 10, marginBottom: 8, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 9, backgroundColor: '#fff' },
  reportResultHeading: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  reportTestName: { flex: 1, color: '#0F172A', fontSize: 12, fontWeight: '700' },
  reportPrice: { color: '#0F172A', fontSize: 11, fontWeight: '800' },
  reportStatusBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 4, marginTop: 7, borderRadius: 12 },
  reportNormal: { backgroundColor: '#DCFCE7' },
  reportAbnormal: { backgroundColor: '#FEE2E2' },
  reportPending: { backgroundColor: '#FEF3C7' },
  reportStatusText: { color: '#334155', fontSize: 9, fontWeight: '700' },
  reportParameterRow: { paddingVertical: 7, marginTop: 6, borderTopWidth: 1, borderTopColor: '#F1F5F9' },
  reportParameterName: { color: '#334155', fontSize: 11, fontWeight: '700' },
  reportParameterValue: { color: '#0F172A', fontSize: 12, fontWeight: '700', marginTop: 2 },
  reportQuickActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 7 },
  reportTotalRow: { flexDirection: 'row', justifyContent: 'space-between', padding: 13, backgroundColor: '#F0FDFA' },
  reportRemarksBlock: { padding: 13, borderTopWidth: 1, borderTopColor: '#E2E8F0' },
  reportFooter: { color: '#64748B', fontSize: 9, textAlign: 'center', padding: 10, borderTopWidth: 1, borderTopColor: '#E2E8F0', backgroundColor: '#F8FAFC' },
  patientReportFooter: { flexDirection: 'row', gap: 8, padding: 12, borderTopWidth: 1, borderTopColor: '#E2E8F0' },
  patientReportAction: { flex: 1 },
  modalTitle: { color: '#0F172A', fontSize: 18, fontWeight: '800' },
  modalSubtitle: {
    color: '#64748B',
    fontSize: 12,
    marginTop: 5,
    marginBottom: 14,
  },
  modalOptions: { maxHeight: 360, marginTop: 12 },
  clinicOption: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F6',
  },
  clinicOptionText: { color: '#334155', fontSize: 14, fontWeight: '600' },
  optionList: { gap: 7, marginVertical: 8 },
  statusOption: {
    minHeight: 41,
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
  },
  statusOptionActive: { borderColor: '#0D9488', backgroundColor: '#F0FDFA' },
  statusOptionText: { color: '#475569', fontSize: 13, fontWeight: '600' },
  statusOptionTextActive: { color: '#0F766E' },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 16,
  },
  cancelButton: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
  },
  cancelText: { color: '#475569', fontSize: 12, fontWeight: '700' },
  primaryButton: {
    minWidth: 110,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: '#0D9488',
  },
  primaryText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  parameterBlock: {
    padding: 11,
    marginTop: 11,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 11,
    backgroundColor: '#F8FAFC',
  },
  parameterHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  parameterTitle: { color: '#334155', fontSize: 12, fontWeight: '700' },
  removeText: { color: '#B91C1C', fontSize: 11, fontWeight: '700' },
  input: {
    minHeight: 43,
    paddingHorizontal: 11,
    paddingVertical: 9,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#DCE5E9',
    borderRadius: 9,
    color: '#0F172A',
    backgroundColor: '#fff',
    fontSize: 13,
  },
  inputRow: { flexDirection: 'row', gap: 8 },
  inputHalf: { flex: 1 },
  multiline: { minHeight: 76, textAlignVertical: 'top', marginTop: 12 },
  addParameterButton: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#E2E8F0',
    borderRadius: 9,
    backgroundColor: '#F8FAFC',
  },
  abnormalToggle: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 1,
    borderColor: '#94A3B8',
    borderRadius: 4,
  },
  checkboxActive: { borderColor: '#0D9488', backgroundColor: '#0D9488' },
});
