import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  bannerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
    gap: 10,
  },
  billingBannerMobile: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    columnGap: 12,
    rowGap: 4,
    marginBottom: 0,
  },
  bannerTitleBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  bannerCopy: { marginLeft: 12, flex: 1 },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#E6F4F1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageIconMobile: { width: 24, height: 24, borderRadius: 0, backgroundColor: 'transparent' },
  bannerTitle: { fontSize: 24, fontWeight: '700', color: '#0F172A' },
  bannerTitleMobile: { fontSize: 24, fontWeight: '700' },
  bannerSubtitle: { fontSize: 14, color: '#64748B', marginTop: 2 },
  createBillButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0D9488',
    paddingHorizontal: 12,
    minHeight: 40,
    borderRadius: 8,
    justifyContent: 'center',
    gap: 4,
  },
  createBillButtonMobile: {
    minHeight: 40,
    alignSelf: 'flex-start',
    marginTop: 8,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: '#20A99B',
  },
  createBillText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  metricCard: {
    width: '48.5%',
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 10,
    marginBottom: 10,
  },
  metricIcon: {
    width: 42,
    height: 42,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricCopy: { flex: 1, minWidth: 0, marginLeft: 9 },
  metricNumber: { fontSize: 17, fontWeight: '800', color: '#0F172A' },
  metricCaption: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '600',
    marginTop: 1,
  },
  statusWrap: { position: 'relative', zIndex: 15 },
  statusButton: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 14,
  },
  statusButtonText: {
    fontSize: 14,
    color: '#334155',
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  statusMenu: {
    position: 'absolute',
    top: 47,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 9,
    elevation: 8,
    zIndex: 20,
  },
  datePickerFlex: { flex: 1, minWidth: 0 },
  listTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  listSubtitle: { fontSize: 12, color: '#64748B', marginTop: 3 },
  listHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  listHeaderActionsMobile: { width: '100%', flexDirection: 'column', alignItems: 'stretch' },
  headerButton: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 9,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  headerButtonText: { color: '#334155', fontSize: 11, fontWeight: '700' },
  headerButtonMobile: { width: '100%', minHeight: 38, justifyContent: 'center' },
  lastRefreshed: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: '#F8FAFC',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    alignItems: 'flex-end',
  },
  lastRefreshedText: { color: '#94A3B8', fontSize: 10 },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 8,
  },
  cardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F1F5F9',
    paddingVertical: 10,
    marginVertical: 10,
    rowGap: 10,
  },
  gridCol: { width: '50%', paddingRight: 7 },
  gridLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: 0.5,
  },
  gridValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
    marginTop: 3,
  },
  gridPhone: { fontSize: 14, color: '#0F172A', marginTop: 3 },
  cardBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  cardMeta: { flex: 1 },
  bottomMeta: { fontSize: 12, color: '#64748B', marginTop: 2 },
  cardActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  viewAction: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#99F6E4',
    backgroundColor: '#F0FDFA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  moreAction: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionMenu: {
    position: 'absolute',
    right: 6,
    bottom: 48,
    minWidth: 170,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 9,
    elevation: 10,
    zIndex: 20,
    overflow: 'hidden',
  },
  menuAction: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  menuActionText: { color: '#334155', fontSize: 12, fontWeight: '600' },
  partial: { backgroundColor: '#DBEAFE' },
  listCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    marginBottom: 20,
  },
  listHeader: {
    minHeight: 62,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  listHeaderMobile: { flexDirection: 'column', alignItems: 'stretch' },
  listTitle: { color: '#0F172A', fontSize: 16, fontWeight: '700' },
  refreshButton: {
    minHeight: 32,
    paddingHorizontal: 10,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 7,
    backgroundColor: '#FFFFFF',
  },
  refreshText: { color: '#334155', fontSize: 11, fontWeight: '700' },
  billList: { padding: 12, gap: 12 },
  gridMetric: { flex: 1, minWidth: 105 },
  metricLabel: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  metricValue: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 3,
  },
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  content: { padding: 16, paddingBottom: 90, gap: 12 },
  heading: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  flex: { flex: 1, minWidth: 0 },
  title: { color: '#0F172A', fontSize: 17, fontWeight: '800' },
  muted: { color: '#64748B', fontSize: 11 },
  primaryButton: {
    minHeight: 40,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#0D9488',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  primaryText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  secondaryButton: {
    minHeight: 40,
    flex: 1,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryText: { color: '#334155', fontSize: 12, fontWeight: '700' },
  filters: {
    width: '100%',
    gap: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
  },
  searchSubmitButton: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  searchSubmitText: { color: '#1E293B', fontSize: 12, fontWeight: '600' },
  searchBox: {
    width: '100%',
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  searchInput: { flex: 1, color: '#1E293B', fontSize: 12, paddingVertical: 7 },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 7,
  },
  filterWrap: { flex: 1, minWidth: 120, position: 'relative', zIndex: 4 },
  filterButton: {
    minHeight: 39,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  filterText: { color: '#334155', fontSize: 11, textTransform: 'capitalize' },
  inlineOptions: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  popover: {
    position: 'absolute',
    top: 43,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    elevation: 8,
  },
  option: {
    minHeight: 37,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  optionText: { color: '#1E293B', fontSize: 12 },
  columnsButton: {
    minHeight: 39,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
  },
  columnsText: { color: '#334155', fontWeight: '700', fontSize: 11 },
  dateFilter: {
    width: '100%',
    flex: 0,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  dateTrigger: {
    flex: 1,
    minHeight: 39,
    justifyContent: 'center',
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  dateTriggerText: { color: '#334155', fontSize: 11 },
  billCard: {
    position: 'relative',
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    gap: 9,
  },
  billNo: { color: '#0F172A', fontSize: 14, fontWeight: '700' },
  patientName: { marginTop: 2, color: '#475569', fontSize: 13 },
  amount: { color: '#0F172A', fontSize: 15, fontWeight: '800' },
  metaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  metaText: { color: '#64748B', fontSize: 10 },
  billStats: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  status: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 14,
  },
  paid: { backgroundColor: '#DCFCE7' },
  pending: { backgroundColor: '#FEF3C7' },
  cancelled: { backgroundColor: '#FEE2E2' },
  statusText: { color: '#334155', fontSize: 10, fontWeight: '700' },
  itemPreview: {
    padding: 9,
    gap: 4,
    borderRadius: 9,
    backgroundColor: '#F8FAFC',
  },
  itemText: { color: '#334155', fontSize: 11 },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingTop: 2 },
  action: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  actionText: { color: '#334155', fontSize: 10, fontWeight: '700' },
  danger: { color: '#DC2626' },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    padding: 24,
  },
  empty: {
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 14,
    backgroundColor: 'rgba(15,23,42,0.58)',
  },
  modalShell: { width: '100%', maxWidth: 520, maxHeight: '94%' },
  createModalBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
  },
  createModalShell: { width: '100%', maxWidth: 380, height: '94%', maxHeight: '94%' },
  createModalCard: {
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    borderTopWidth: 3,
    borderTopColor: '#14B8A6',
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
  },
  createModalHeader: {
    minHeight: 80,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  createHeaderIcon: {
    width: 39,
    height: 39,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0D9488',
  },
  createModalScroll: { flex: 1, minHeight: 0 },
  createModalContent: { paddingBottom: 0 },
  createSection: {
    padding: 15,
    gap: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  createSectionTint: {
    padding: 15,
    gap: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  createSectionHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 11, marginBottom: 2 },
  createSectionHeaderCompact: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  createSectionIcon: {
    width: 31,
    height: 31,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0FDFA',
  },
  createSectionIconBlue: {
    width: 31,
    height: 31,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EFF6FF',
  },
  createSectionTitle: { color: '#0F172A', fontSize: 12, fontWeight: '700' },
  createSectionSubtitle: { color: '#64748B', fontSize: 10, lineHeight: 14, marginTop: 2 },
  createSectionSubtitleIndented: { color: '#64748B', fontSize: 11, marginLeft: 42, marginTop: -2 },
  createLabel: { color: '#334155', fontSize: 12, fontWeight: '500' },
  createOptional: { color: '#64748B', fontWeight: '400' },
  required: { color: '#DC2626', fontWeight: '700' },
  createInputWrap: { position: 'relative', justifyContent: 'center' },
  createInputWithIcon: { paddingLeft: 32 },
  inputWithClear: { paddingRight: 34 },
  inputLeadingIcon: { position: 'absolute', left: 11, zIndex: 1 },
  inputClear: { position: 'absolute', right: 10, padding: 5 },
  selectedPatientSummary: { color: '#059669', fontSize: 11, marginTop: 1 },
  createSuggestions: { borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 9, backgroundColor: '#FFFFFF', overflow: 'hidden' },
  createSuggestion: { padding: 10, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  createSuggestionTitle: { color: '#1E293B', fontSize: 11, fontWeight: '600' },
  prescriptionMeta: { color: '#64748B', fontSize: 10, lineHeight: 15 },
  prescriptionMetaValue: { color: '#334155', fontWeight: '600' },
  prescriptionBodyText: { color: '#1E293B', fontSize: 11, lineHeight: 16 },
  prescriptionMedicineItem: { gap: 4, padding: 8, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 8, backgroundColor: '#F8FAFC' },
  prescriptionCustomMedicine: { borderColor: '#FCD34D', backgroundColor: '#FFFBEB' },
  prescriptionMedicineName: { color: '#1E293B', fontSize: 11, fontWeight: '600' },
  prescriptionCustomText: { color: '#B45309', fontSize: 10, fontWeight: '600' },
  prescriptionCountBadge: { color: '#475569', fontSize: 10, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 13, backgroundColor: '#FFFFFF' },
  prescriptionPagination: { gap: 8, paddingTop: 8 },
  prescriptionPageControls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  prescriptionPageButton: { minHeight: 31, justifyContent: 'center', paddingHorizontal: 10, borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 8, backgroundColor: '#FFFFFF' },
  prescriptionPageDisabled: { opacity: 0.45 },
  prescriptionPageText: { color: '#334155', fontSize: 10, fontWeight: '600' },
  addMedicineButton: {
    minHeight: 36,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
  },
  addMedicineText: { color: '#0F172A', fontSize: 11, fontWeight: '600' },
  emptyMedicineBox: {
    minHeight: 61,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#CBD5E1',
    borderRadius: 9,
    backgroundColor: '#F8FAFC',
  },
  createSelect: {
    minHeight: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
  },
  createSelectText: { color: '#1E293B', fontSize: 12 },
  createSelectOptions: { borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 9, backgroundColor: '#FFFFFF', overflow: 'hidden' },
  createSelectOption: { minHeight: 38, justifyContent: 'center', paddingHorizontal: 11, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  createModalFooter: { paddingHorizontal: 15, paddingTop: 10, paddingBottom: 11, borderTopWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#FFFFFF' },
  amountDueRow: { minHeight: 29, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 7 },
  amountDueLabel: { color: '#64748B', fontSize: 10, letterSpacing: 0.4 },
  amountDueValue: { color: '#0F172A', fontSize: 15, fontWeight: '800' },
  createFooterButtons: { flexDirection: 'row', gap: 8 },
  createFooterPrimary: { flex: 1 },
  modalCard: {
    maxHeight: '100%',
    overflow: 'hidden',
    borderTopWidth: 3,
    borderTopColor: '#14B8A6',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
  },
  invoiceModalBackdrop: { padding: 16 },
  invoiceModalCard: {
    width: '100%',
    maxWidth: 620,
    maxHeight: '94%',
    paddingBottom: 0,
    borderRadius: 12,
    borderTopWidth: 3,
    borderTopColor: '#20B6A7',
    flexDirection: 'column',
  },
  invoiceModalCardMobile: { height: '94%' },
  invoiceHeader: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  invoiceHeaderIcon: {
    width: 38,
    height: 38,
    borderRadius: 9,
    backgroundColor: '#0D9488',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  invoiceHeaderCopy: { flex: 1 },
  invoiceHeaderTitle: { color: '#0F172A', fontSize: 15, fontWeight: '700' },
  invoiceHeaderSubtitle: { color: '#64748B', fontSize: 12, marginTop: 3 },
  invoiceCloseIcon: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center' },
  invoiceBodyScroll: { flex: 1, backgroundColor: '#F1F5F9' },
  invoiceBodyScrollContent: { padding: 12 },
  invoiceDocument: { width: '100%', overflow: 'hidden', borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#FFFFFF' },
  invoiceDocumentContent: { padding: 16, gap: 16 },
  invoiceTopRow: { gap: 14, paddingBottom: 18, borderBottomWidth: 2, borderBottomColor: '#0D9488' },
  invoiceClinicBlock: { gap: 3 },
  invoiceClinicName: { color: '#0F172A', fontSize: 16, fontWeight: '900' },
  invoiceClinicTagline: { color: '#0F766E', fontSize: 10, marginTop: 1 },
  invoiceClinicContact: { color: '#64748B', fontSize: 11, marginTop: 3 },
  invoiceBillMeta: { alignItems: 'flex-start', gap: 4, marginTop: 6 },
  invoiceType: { color: '#0F766E', fontSize: 10, fontWeight: '800' },
  invoiceBillNumber: { color: '#0F172A', fontSize: 15, fontWeight: '800' },
  invoiceMetaText: { color: '#475569', fontSize: 11, lineHeight: 17 },
  invoicePatientSection: { gap: 18, paddingBottom: 18, borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  invoiceMetaColumn: { flex: 1, gap: 3 },
  invoiceSectionLabel: { color: '#64748B', fontSize: 10, fontWeight: '800' },
  invoicePatientName: { color: '#0F172A', fontSize: 13, fontWeight: '800', marginTop: 2 },
  invoicePaymentBanner: { gap: 8, paddingHorizontal: 13, paddingVertical: 12, borderWidth: 1, borderColor: '#99F6E4', borderRadius: 9, backgroundColor: '#F0FDFA' },
  invoicePaymentText: { color: '#334155', fontSize: 11 },
  invoiceStrong: { color: '#0F172A', fontWeight: '700' },
  invoiceStatusPill: { alignSelf: 'flex-start', borderRadius: 20, paddingHorizontal: 9, paddingVertical: 4 },
  invoicePaidPill: { backgroundColor: '#DCFCE7' },
  invoiceDuePill: { backgroundColor: '#FEF3C7' },
  invoiceStatusText: { color: '#15803D', fontSize: 10, fontWeight: '700' },
  invoiceSectionTitle: { color: '#64748B', fontSize: 10, fontWeight: '800', marginTop: 2 },
  invoiceItemCard: { gap: 8, padding: 11, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 9, backgroundColor: '#FFFFFF' },
  invoiceItemTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
  invoiceItemName: { flex: 1, color: '#0F172A', fontSize: 12, fontWeight: '600' },
  invoiceItemTotal: { color: '#0F172A', fontSize: 12, fontWeight: '800' },
  invoiceItemCode: { color: '#64748B', fontSize: 10 },
  invoiceItemMeta: { flexDirection: 'row', gap: 8 },
  invoiceItemValue: { color: '#334155', fontSize: 10, marginTop: 2 },
  invoiceSummary: { gap: 10, marginTop: 4, paddingTop: 17, borderTopWidth: 1, borderTopColor: '#E2E8F0' },
  invoicePreparedBy: { color: '#64748B', fontSize: 11, marginTop: 3 },
  invoiceTotals: { gap: 9, marginTop: 3 },
  invoiceTotalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  invoiceTotalLabel: { color: '#475569', fontSize: 11 },
  invoiceTotalValue: { color: '#475569', fontSize: 11 },
  invoiceGrandTotal: { paddingTop: 10, borderTopWidth: 1, borderTopColor: '#CBD5E1' },
  invoiceGrandLabel: { color: '#0F172A', fontSize: 13, fontWeight: '800' },
  invoiceGrandValue: { color: '#0F172A', fontSize: 13, fontWeight: '800' },
  invoicePaidLabel: { color: '#0F766E', fontSize: 11 },
  invoicePaidValue: { color: '#0F766E', fontSize: 11, fontWeight: '700' },
  invoiceBalanceLabel: { color: '#E11D48', fontSize: 11, fontWeight: '700' },
  invoiceBalanceValue: { color: '#E11D48', fontSize: 11, fontWeight: '700' },
  invoiceDocumentFooter: { paddingHorizontal: 14, paddingVertical: 11, backgroundColor: '#F8FAFC', borderTopWidth: 1, borderTopColor: '#E2E8F0' },
  invoiceFooterNote: { color: '#64748B', fontSize: 10, textAlign: 'center' },
  invoiceActionFooter: { paddingHorizontal: 14, paddingTop: 10, paddingBottom: 12, backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E2E8F0' },
  invoiceActionButtonsRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  invoiceActionButton: { flex: 1, minWidth: 0 },
  invoiceCloseAction: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 9, borderWidth: 1, borderColor: '#CBD5E1', backgroundColor: '#F8FAFC' },
  invoiceCloseActionText: { color: '#1E293B', fontSize: 13, fontWeight: '600' },
  invoiceDownloadButton: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 9, backgroundColor: '#0D9488' },
  invoiceDownloadButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '800' },
  modalHeader: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
  },
  modalTitle: { color: '#1E293B', fontSize: 15, fontWeight: '800' },
  close: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalScroll: { flexShrink: 1, maxHeight: 600 },
  modalContent: { gap: 12, padding: 14 },
  modalFooter: {
    flexDirection: 'row',
    gap: 9,
    padding: 12,
    borderTopWidth: 1,
    borderColor: '#E2E8F0',
  },
  field: { gap: 5 },
  label: { color: '#334155', fontSize: 12, fontWeight: '500' },
  input: {
    minHeight: 41,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    color: '#1E293B',
    fontSize: 12,
  },
  selectedPatient: {
    minHeight: 51,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 9,
    borderRadius: 10,
    backgroundColor: '#F0FDFA',
  },
  suggestion: { padding: 9, borderBottomWidth: 1, borderColor: '#E2E8F0' },
  lineCard: {
    gap: 10,
    padding: 11,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  lineField: {
    flex: 1,
    gap: 5,
  },
  lineHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  lineInputs: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  lineInput: { minWidth: 0 },
  lineTotalField: { width: '48%', gap: 5 },
  lineTotalValue: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 11,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    color: '#0F172A',
    fontSize: 12,
  },
  lineRemoveRow: {
    marginTop: 1,
    paddingTop: 8,
    alignItems: 'flex-end',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  lineRemoveButton: { width: 28, height: 24, alignItems: 'center', justifyContent: 'center' },
  methodButton: {
    minHeight: 34,
    paddingHorizontal: 10,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 9,
  },
  methodActive: { borderColor: '#0D9488', backgroundColor: '#CCFBF1' },
  methodActiveText: { color: '#0F766E', fontWeight: '800' },
  totalsBox: {
    gap: 9,
    padding: 11,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  info: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  bold: { fontWeight: '800' },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
  },
  disabled: { opacity: 0.65 },

  extractedInline1: { minWidth: 140 },
  extractedInlineDanger: { color: '#DC2626' },
});
