import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  content: {
    width: '100%',
    maxWidth: 900,
    alignSelf: 'center',
    padding: 14,
    paddingBottom: 28,
    gap: 10,
  },
  listHeader: { gap: 10, marginBottom: 3 },
  bannerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  bannerTitleBlock: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#E6F4F1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerTitleCopy: { flex: 1, minWidth: 0, marginLeft: 12 },
  bannerTitle: { color: '#0F172A', fontSize: 20, fontWeight: '800' },
  bannerSubtitle: { color: '#64748B', fontSize: 13, marginTop: 2 },
  patientHeaderActions: { flexDirection: 'row', gap: 8 },
  addButton: {
    flex: 1,
    minHeight: 39,
    paddingHorizontal: 11,
    borderRadius: 9,
    backgroundColor: '#26A69A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  addButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '800' },
  exportButton: {
    flex: 1,
    minHeight: 39,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 9,
    backgroundColor: '#F8FAFC',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  exportButtonText: { color: '#1E293B', fontSize: 12, fontWeight: '600' },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 1,
  },
  sectionTitleCopy: { flex: 1 },
  sectionTitle: { fontSize: 17, fontWeight: '900', color: '#0F172A' },
  sectionSubtitle: { marginTop: 2, fontSize: 11, color: '#64748B' },
  searchCard: {
    minHeight: 39,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 12,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  searchInput: { flex: 1, paddingVertical: 10, fontSize: 12, color: '#0F172A' },
  resultsHeading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 43,
    marginTop: 1,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
  },
  resultsTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  resultsTitle: { fontSize: 13, fontWeight: '800', color: '#0F172A' },
  patientCard: {
    padding: 11,
    borderRadius: 13,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  patientInfo: { minWidth: 0, gap: 6 },
  patientNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  patientIdentity: { flex: 1, minWidth: 0, gap: 3 },
  patientName: { fontSize: 13, fontWeight: '700', color: '#1E293B' },
  moreButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  patientDetails: { gap: 6, marginTop: 8 },
  patientDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  patientDetailLabel: { color: '#718096', fontSize: 10 },
  patientDetailValue: {
    color: '#253247',
    fontSize: 10,
    flexShrink: 1,
    textAlign: 'right',
  },
  activeStatus: { backgroundColor: '#DCFCE7' },
  inactiveStatus: { backgroundColor: '#F1F5F9' },
  activeStatusText: { color: '#15803D' },
  inactiveStatusText: { color: '#64748B' },
  patientMeta: { fontSize: 10, color: '#64748B' },
  actionOverlay: { flex: 1 },
  actionMenu: {
    position: 'absolute',
    width: 190,
    padding: 6,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DCE4EC',
    elevation: 10,
    shadowColor: '#0F172A',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  actionMenuTitle: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: '800',
    color: '#334155',
  },
  actionMenuItem: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 8,
    borderRadius: 7,
  },
  actionMenuItemHighlighted: { backgroundColor: '#DDF5F2' },
  actionMenuText: { color: '#334155', fontSize: 11 },
  actionMenuTextHighlighted: { color: '#0D9488' },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 42,
    gap: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
  },
  permissionState: {
    marginHorizontal: 16,
    marginTop: 20,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
  },
  noViewContent: { flex: 1 },
  emptyIcon: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: '#E6F4F1',
  },
  emptyTitle: { fontSize: 15, fontWeight: '800', color: '#334155' },
  emptySubtitle: {
    fontSize: 11,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 17,
  },
  paginationWrap: {
    marginTop: 5,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 6,
  },
  footerSpacer: { height: 36 },
});
