import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  menuActionHighlighted: { backgroundColor: '#DDF5F2' },
  menuActionTextHighlighted: { color: '#0F766E', fontWeight: '600' },
  stockModalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    backgroundColor: 'rgba(15,23,42,0.5)',
  },
  stockModalShell: { width: '100%', maxWidth: 380, maxHeight: '90%' },
  stockModalCard: { borderRadius: 14 },
  stockModalHeader: {
    minHeight: 78,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 48,
    borderBottomWidth: 0,
  },
  stockHeaderCopy: { alignItems: 'center', gap: 5 },
  stockModalSubtitle: { color: '#718096', fontSize: 12 },
  stockCloseButton: {
    position: 'absolute',
    top: 8,
    right: 9,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stockFormScroll: { flexShrink: 1, maxHeight: 350 },
  stockFormContent: {
    gap: 22,
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 22,
  },
  stockOptions: { flexDirection: 'row', gap: 14 },
  stockOption: {
    flex: 1,
    minWidth: 0,
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 11,
    backgroundColor: '#F8FAFC',
  },
  stockOptionActive: { borderColor: '#26A69A', backgroundColor: '#26A69A' },
  stockOptionText: { color: '#1E293B', fontSize: 12, fontWeight: '600' },
  stockOptionTextActive: { color: '#FFFFFF', fontWeight: '700' },
  stockQuantityField: { gap: 8 },
  stockQuantityLabel: { color: '#1E293B', fontSize: 12, fontWeight: '500' },
  stockQuantityInput: {
    minHeight: 46,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    fontSize: 14,
  },
  stockModalFooter: {
    gap: 8,
    paddingHorizontal: 22,
    paddingTop: 4,
    paddingBottom: 18,
  },
  stockSaveButton: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 10,
    backgroundColor: '#26A69A',
  },
  stockCancelButton: {
    minHeight: 39,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  actionMenuOverlay: { flex: 1 },
  actionMenuCard: {
    position: 'absolute',
    width: 190,
    padding: 4,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    elevation: 12,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
  },
  menuDivider: { height: 1, marginVertical: 3, backgroundColor: '#F1F5F9' },
  medicineModalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 18,
    backgroundColor: 'rgba(15,23,42,0.62)',
  },
  medicineModalShell: { width: '100%', maxWidth: 430, maxHeight: '88%' },
  medicineModalTitle: { fontSize: 17, fontWeight: '700', color: '#111827' },
  medicineField: { gap: 7, marginBottom: 3 },
  medicineFieldLabel: { color: '#334155', fontSize: 13, fontWeight: '600' },
  requiredStar: { color: '#EF4444', fontWeight: '700' },
  medicineFormInput: {
    minHeight: 48,
    paddingHorizontal: 12,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
    fontSize: 14,
  },
  medicineDateTriggerText: { fontSize: 14, color: '#718096' },
  medicineModalCard: { maxHeight: '100%' },
  medicineModalHeader: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
  },
  medicineModalIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: '#0D9488',
  },
  modalHeaderCopy: { gap: 3 },
  medicineModalSubtitle: { color: '#718096', fontSize: 12 },
  medicineFormScroll: { flexShrink: 1, maxHeight: 650 },
  medicineFormContent: { gap: 15, padding: 15, paddingBottom: 18 },
  columnsWrap: { position: 'relative', zIndex: 2 },
  columnsPopover: {
    position: 'absolute',
    top: 43,
    right: 0,
    width: 235,
    maxHeight: 360,
    padding: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    elevation: 12,
    zIndex: 40,
  },
  columnsPopoverTitle: {
    paddingHorizontal: 8,
    paddingVertical: 7,
    color: '#64748B',
    fontSize: 10,
    fontWeight: '800',
  },
  columnOption: {
    minHeight: 37,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 8,
  },
  columnsReset: {
    minHeight: 35,
    justifyContent: 'center',
    paddingHorizontal: 8,
    borderTopWidth: 1,
    borderColor: '#E2E8F0',
  },
  columnsResetText: { color: '#0F766E', fontSize: 10, fontWeight: '700' },
  filterSelectWrap: { flex: 1, minWidth: 0, position: 'relative', zIndex: 1 },
  filterSelectWrapTop: { zIndex: 20 },
  filterPopover: {
    position: 'absolute',
    top: 43,
    left: 0,
    right: 0,
    maxHeight: 230,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    elevation: 10,
    zIndex: 30,
  },
  filterOption: {
    minHeight: 39,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  filterOptionText: { flex: 1, color: '#334155', fontSize: 11 },
  actionRow: { flexDirection: 'row', gap: 8 },
  patientStylePrimaryButton: {
    flex: 1,
    minHeight: 39,
    paddingHorizontal: 11,
    borderRadius: 9,
    backgroundColor: '#26A69A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  patientStylePrimaryText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  patientStyleSecondaryButton: {
    flex: 1,
    minHeight: 39,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 9,
    backgroundColor: '#F8FAFC',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  patientStyleSecondaryText: {
    color: '#1E293B',
    fontSize: 12,
    fontWeight: '600',
  },
  filtersCard: {
    gap: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 13,
    backgroundColor: '#FFFFFF',
  },
  filterSelectRow: { flexDirection: 'row', gap: 8 },
  filterSelect: {
    flex: 1,
    minWidth: 0,
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 5,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  filterSelectText: { flex: 1, color: '#1E293B', fontSize: 11 },
  columnsButton: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  columnsButtonText: { color: '#1E293B', fontSize: 11, fontWeight: '700' },
  columnCheck: {
    width: 19,
    height: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 5,
  },
  columnCheckActive: { borderColor: '#0D9488', backgroundColor: '#0D9488' },
  columnsDone: {
    minHeight: 39,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    borderRadius: 10,
    backgroundColor: '#0D9488',
  },
  columnsDoneText: { color: '#FFFFFF', fontSize: 12, fontWeight: '800' },
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  content: { padding: 14, paddingBottom: 90, gap: 12 },
  pageHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 3,
  },
  headingIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    backgroundColor: '#CCFBF1',
  },
  headingText: { flex: 1 },
  pageTitle: { color: '#0F172A', fontSize: 18, fontWeight: '800' },
  muted: { color: '#64748B', fontSize: 11 },
  headerActions: { flexDirection: 'row', gap: 6 },
  importButton: {
    minHeight: 39,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 9,
    borderWidth: 1,
    borderColor: '#99F6E4',
    borderRadius: 11,
    backgroundColor: '#F0FDFA',
  },
  importButtonText: { color: '#0F766E', fontSize: 10, fontWeight: '800' },
  addButton: {
    minHeight: 39,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 10,
    borderRadius: 11,
    backgroundColor: '#0D9488',
  },
  addButtonText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  statCard: {
    width: '48%',
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
  },
  statIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
  },
  statTeal: { backgroundColor: '#CCFBF1' },
  statGreen: { backgroundColor: '#DCFCE7' },
  statAmber: { backgroundColor: '#FEF3C7' },
  statBlue: { backgroundColor: '#DBEAFE' },
  statCopy: { flex: 1, minWidth: 0 },
  statValue: { color: '#1E293B', fontSize: 14, fontWeight: '800' },
  statLabel: { marginTop: 3, color: '#64748B', fontSize: 9 },
  searchBox: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 13,
    backgroundColor: '#FFFFFF',
  },
  searchInput: { flex: 1, paddingVertical: 8, color: '#1E293B', fontSize: 12 },
  filterLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  lowStockToggle: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
  },
  lowStockToggleActive: { borderColor: '#FCD34D', backgroundColor: '#FFFBEB' },
  lowStockText: { color: '#475569', fontSize: 10, fontWeight: '700' },
  lowStockTextActive: { color: '#B45309' },
  countBadge: {
    minWidth: 19,
    height: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
  },
  countText: { color: '#475569', fontSize: 9, fontWeight: '800' },
  pageHint: { color: '#94A3B8', fontSize: 10 },
  chipRow: { flexDirection: 'row', gap: 6, paddingVertical: 1 },
  filterChip: {
    minHeight: 29,
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
  },
  filterChipActive: { borderColor: '#99F6E4', backgroundColor: '#CCFBF1' },
  filterChipText: { color: '#475569', fontSize: 9, fontWeight: '600' },
  filterChipTextActive: { color: '#0F766E', fontWeight: '800' },
  listHeader: {
    minHeight: 43,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 3,
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
  },
  listTitle: { color: '#1E293B', fontSize: 14, fontWeight: '800' },
  cards: { gap: 10 },
  card: {
    padding: 13,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    elevation: 1,
  },
  cardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginBottom: 11,
  },
  medicineIcon: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#F0FDFA',
  },
  cardTitleBlock: { flex: 1, minWidth: 0 },
  medicineName: { color: '#1E293B', fontSize: 13, fontWeight: '800' },
  medicineForm: { marginTop: 3, color: '#64748B', fontSize: 10 },
  moreButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
  },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  infoTile: {
    width: '48%',
    minHeight: 58,
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 11,
    backgroundColor: '#F8FAFC',
  },
  infoLabel: {
    color: '#64748B',
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  infoValue: { color: '#1E293B', fontSize: 11, fontWeight: '700' },
  statusPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 12,
  },
  inStock: { backgroundColor: '#DCFCE7' },
  lowStock: { backgroundColor: '#FEF3C7' },
  outStock: { backgroundColor: '#FEE2E2' },
  statusText: { color: '#15803D', fontSize: 9, fontWeight: '800' },
  lowStatusText: { color: '#B45309' },
  batchLine: { marginTop: 9, color: '#64748B', fontSize: 9 },
  loading: {
    minHeight: 160,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  empty: {
    minHeight: 170,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
  },
  emptyTitle: { color: '#1E293B', fontSize: 13, fontWeight: '800' },
  permissionBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    padding: 24,
  },
  filePicker: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#5EEAD4',
    borderRadius: 12,
    backgroundColor: '#F0FDFA',
  },
  filePickerText: { color: '#0F766E', fontSize: 11, fontWeight: '800' },
  selectedFile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    padding: 10,
    borderWidth: 1,
    borderColor: '#CCFBF1',
    borderRadius: 11,
    backgroundColor: '#F0FDFA',
  },
  fileCopy: { flex: 1 },
  fileName: { color: '#1E293B', fontSize: 10, fontWeight: '800' },
  menuBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 28,
    backgroundColor: 'rgba(15,23,42,0.32)',
  },
  menuCard: {
    width: '100%',
    maxWidth: 300,
    padding: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    elevation: 12,
  },
  menuTitle: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: '#64748B',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  menuAction: {
    minHeight: 43,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  menuActionText: { color: '#334155', fontSize: 12, fontWeight: '600' },
  destructiveText: { color: '#EF4444' },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 12,
    backgroundColor: 'rgba(15,23,42,0.62)',
  },
  modalShell: { width: '100%', maxWidth: 520, maxHeight: '94%' },
  modalCard: {
    overflow: 'hidden',
    borderTopWidth: 3,
    borderTopColor: '#14B8A6',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    elevation: 20,
  },
  modalHeader: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
  },
  modalHeading: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  modalIcon: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#CCFBF1',
  },
  modalTitle: { color: '#1E293B', fontSize: 15, fontWeight: '800' },
  closeButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formScroll: { flexGrow: 0, maxHeight: 590 },
  formContent: { gap: 8, padding: 14, paddingBottom: 18 },
  formSection: {
    marginBottom: 2,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
    color: '#64748B',
    fontSize: 11,
    fontWeight: '800',
  },
  field: { flex: 1, minWidth: 120, gap: 4 },
  label: { marginBottom: 4, color: '#334155', fontSize: 10, fontWeight: '700' },
  input: {
    minHeight: 40,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    color: '#1E293B',
    fontSize: 11,
  },
  focusedInput: { borderWidth: 2, borderColor: '#14B8A6' },
  dateTrigger: {
    minHeight: 40,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  dateTriggerText: { color: '#334155', fontSize: 10 },
  twoColumns: { flexDirection: 'row', gap: 9 },
  formHint: { color: '#64748B', fontSize: 9, lineHeight: 14 },
  modalFooter: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderTopWidth: 1,
    borderColor: '#E2E8F0',
  },
  cancelButton: {
    flex: 1,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  cancelText: { color: '#334155', fontSize: 11, fontWeight: '700' },
  saveButton: {
    flex: 1,
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 10,
    backgroundColor: '#0D9488',
  },
  saveText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  disabledButton: { opacity: 0.65 },
  stockSummary: {
    gap: 5,
    padding: 11,
    borderRadius: 11,
    backgroundColor: '#F0FDFA',
  },
  stockMedicineName: { color: '#0F172A', fontSize: 12, fontWeight: '800' },
  segmentRow: { gap: 8 },
  segment: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  segmentActive: { borderColor: '#5EEAD4', backgroundColor: '#F0FDFA' },
  segmentText: { color: '#475569', fontSize: 11 },
  segmentTextActive: { color: '#0F766E', fontWeight: '800' },
  importError: {
    padding: 10,
    borderRadius: 9,
    backgroundColor: '#FEF2F2',
    color: '#B91C1C',
    fontSize: 11,
  },
  importPreviewBox: {
    gap: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  importPreviewRow: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    borderTopWidth: 1,
    borderColor: '#E2E8F0',
  },

  extractedInline1: { maxHeight: 170 },
});
