import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc' },
  content: { padding: 12, paddingBottom: 36 },
  flex: { flex: 1 },
  hero: {
    backgroundColor: '#fff',
    borderRadius: 17,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#dbe2ea',
    elevation: 1,
  },
  heroTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  videoIconBox: {
    width: 48,
    height: 48,
    borderRadius: 13,
    backgroundColor: '#CCFBF1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoIconCurrency: {
    position: 'absolute',
    top: 18,
    left: 18,
  },
  eyebrow: {
    alignSelf: 'flex-start',
    backgroundColor: '#eef2f5',
    color: '#475569',
    fontSize: 11,
    fontWeight: '600',
    borderRadius: 20,
    paddingHorizontal: 11,
    paddingVertical: 4,
    overflow: 'hidden',
    marginBottom: 5,
  },
  title: { fontSize: 22, fontWeight: '800', color: '#0F172A' },
  subtitle: { fontSize: 13, color: '#64748B', marginTop: 9, lineHeight: 19 },
  refreshButton: {
    height: 40,
    borderRadius: 11,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    flexDirection: 'row',
    gap: 7,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 13,
  },
  refreshButtonText: { color: '#1f2937', fontSize: 12, fontWeight: '600' },
  refreshedText: { color: '#71839d', fontSize: 10, marginTop: 9 },
  openAppointments: {
    alignSelf: 'flex-start',
    height: 40,
    paddingHorizontal: 15,
    borderRadius: 11,
    backgroundColor: '#27a99d',
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 13,
  },
  openAppointmentsText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  stat: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 21,
    borderWidth: 1,
    borderColor: '#dbe2ea',
    elevation: 1,
    marginBottom: 15,
    minHeight: 128,
  },
  statLabel: { color: '#71839d', fontSize: 12 },
  statValue: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1f2937',
    marginTop: 9,
  },
  statDescription: {
    color: '#71839d',
    fontSize: 12,
    marginTop: 9,
    lineHeight: 18,
  },
  tabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    marginTop: 7,
    marginBottom: 12,
  },
  tab: {
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 13,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
  },
  activeTab: { backgroundColor: '#27a99d', borderColor: '#27a99d' },
  tabText: { fontSize: 12, fontWeight: '600', color: '#71839d' },
  activeTabText: { color: '#fff' },
  queueHeading: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#dbe2ea',
    padding: 19,
    marginTop: 2,
    marginBottom: 10,
  },
  sectionTitle: { color: '#1f2937', fontSize: 18, fontWeight: '700' },
  sectionDescription: {
    color: '#71839d',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 5,
  },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: '#fff',
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 46,
    marginBottom: 12,
  },
  searchInput: { flex: 1, color: '#0f172a', fontSize: 14 },
  queueCard: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#dbe2ea',
    borderRadius: 15,
    padding: 16,
    marginBottom: 12,
    elevation: 1,
  },
  queueCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    paddingBottom: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#eef2f6',
  },
  consultation: { color: '#71839d', fontSize: 12, marginTop: 5 },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
  },
  queueDetails: { gap: 13, paddingTop: 14 },
  queueDetail: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  queueDetailText: { flex: 1 },
  detailLabel: { color: '#71839d', fontSize: 11, marginBottom: 3 },
  detailValue: { color: '#475569', fontSize: 13, fontWeight: '600' },
  historyCard: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#dbe2ea',
    borderRadius: 15,
    padding: 16,
    marginBottom: 12,
    elevation: 1,
  },
  historyHeader: {
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eef2f6',
  },
  historyIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 7,
  },
  completedBadge: { backgroundColor: '#27a99d', borderColor: '#27a99d' },
  completedText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'lowercase',
  },
  appointmentBadge: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#dbe2ea',
    backgroundColor: '#f8fafc',
  },
  appointmentBadgeText: { color: '#334155', fontSize: 11, fontWeight: '600' },
  historyDetails: { gap: 12, paddingTop: 13 },
  historyDetail: { flex: 1, minWidth: 0 },
  historyDetailLabel: { color: '#71839d', fontSize: 11, marginBottom: 4 },
  historyDetailValue: { color: '#52657f', fontSize: 13, lineHeight: 19 },
  historySummaryRow: { flexDirection: 'row', gap: 16 },
  historyActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    paddingTop: 13,
    marginTop: 13,
    borderTopWidth: 1,
    borderTopColor: '#eef2f6',
  },
  iconAction: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dbe2ea',
    backgroundColor: '#fff',
  },
  historyCallButton: {
    minWidth: 94,
    height: 42,
    paddingHorizontal: 14,
    borderRadius: 11,
    backgroundColor: '#27a99d',
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  billingCard: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#dbe2ea',
    borderRadius: 15,
    padding: 16,
    marginBottom: 12,
    elevation: 1,
  },
  billingDetails: { gap: 12, paddingTop: 13 },
  billingActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 8,
    paddingTop: 13,
    marginTop: 13,
    borderTopWidth: 1,
    borderTopColor: '#eef2f6',
  },
  card: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 16,
    padding: 15,
    marginBottom: 11,
  },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ccfbf1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  patient: { fontSize: 15, fontWeight: '700', color: '#0f172a' },
  muted: { color: '#64748b', fontSize: 12, marginTop: 3 },
  status: { fontWeight: '700', fontSize: 11, textTransform: 'capitalize' },
  divider: { height: 1, backgroundColor: '#e2e8f0', marginVertical: 12 },
  detail: {
    color: '#475569',
    fontSize: 12,
    marginTop: 7,
    flexDirection: 'row',
    alignItems: 'center',
  },
  reason: {
    color: '#475569',
    fontSize: 12,
    marginTop: 10,
    fontStyle: 'italic',
  },
  primaryButton: {
    backgroundColor: '#0f766e',
    height: 44,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  primaryText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  disabled: { opacity: 0.45 },
  cardActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 13,
    flexWrap: 'wrap',
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  secondaryText: { fontSize: 12, color: '#0f766e', fontWeight: '700' },
  refundText: { fontSize: 12, color: '#b91c1c', fontWeight: '700' },
  primarySmall: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#0f766e',
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 9,
  },
  primarySmallText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  pagination: { gap: 9, paddingVertical: 12 },
  pageSizeOptions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  pageSizeButton: {
    minWidth: 34,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dbe2ea',
    backgroundColor: '#fff',
  },
  pageSizeButtonActive: { backgroundColor: '#e6fffb', borderColor: '#27a99d' },
  pageSizeText: { color: '#64748b', fontSize: 11, fontWeight: '600' },
  pageSizeTextActive: { color: '#0f766e', fontWeight: '800' },
  pageNavigation: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  pageButton: {
    minHeight: 36,
    paddingHorizontal: 10,
    justifyContent: 'center',
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#dbe2ea',
    backgroundColor: '#fff',
  },
  pageButtonText: { color: '#334155', fontSize: 11, fontWeight: '700' },
  pageLabel: { color: '#64748b', fontSize: 10 },
  loadingIndicator: { marginTop: 36 },
  empty: {
    padding: 28,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#cbd5e1',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#fff',
    marginTop: 4,
  },
  emptyTitle: { color: '#0f172a', fontWeight: '700', fontSize: 15 },
  errorBox: {
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#fef2f2',
    marginBottom: 12,
  },
  errorText: { color: '#b91c1c', fontSize: 13 },
  retry: { color: '#0f766e', fontWeight: '700', marginTop: 6 },
  refresh: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 7,
    paddingVertical: 16,
  },
  refreshText: { color: '#0f766e', fontWeight: '700', fontSize: 13 },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15,23,42,.45)',
  },
  modal: {
    maxHeight: '84%',
    backgroundColor: '#fff',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    marginBottom: 4,
  },
  modalTitle: { fontSize: 18, fontWeight: '800', color: '#0f172a' },
  refundButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#b91c1c',
    padding: 13,
    borderRadius: 11,
    marginTop: 16,
  },
  invoiceModal: {
    width: '100%',
    maxHeight: '94%',
    backgroundColor: '#f1f5f9',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderTopWidth: 4,
    borderTopColor: '#0f9f93',
    overflow: 'hidden',
  },
  invoiceModalHeader: {
    minHeight: 68,
    paddingHorizontal: 17,
    paddingVertical: 13,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  invoiceDialogTitle: { color: '#0f172a', fontSize: 18, fontWeight: '800' },
  invoiceDialogSubtitle: { color: '#64748b', fontSize: 11, marginTop: 4 },
  closeBillButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  invoiceScroll: { flexShrink: 1 },
  invoiceScrollContent: { padding: 12 },
  invoiceSheet: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 16,
  },
  invoiceClinicHeader: {
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#0f9f93',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  invoiceClinicInfo: {
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  clinicLogo: { width: 48, height: 48 },
  clinicName: { color: '#020617', fontSize: 18, fontWeight: '800' },
  invoiceServiceLabel: {
    color: '#0f766e',
    fontSize: 9,
    fontWeight: '800',
    marginTop: 3,
  },
  clinicContact: {
    color: '#64748b',
    fontSize: 10,
    lineHeight: 15,
    marginTop: 3,
  },
  invoiceNumberBlock: { alignItems: 'flex-end', maxWidth: '42%' },
  invoiceNumberLabel: {
    color: '#0f766e',
    fontSize: 8,
    fontWeight: '800',
    textAlign: 'right',
  },
  invoiceNumber: {
    color: '#020617',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 4,
  },
  invoiceMeta: { color: '#64748b', fontSize: 9, marginTop: 3 },
  billParties: {
    flexDirection: 'row',
    gap: 14,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  billParty: { flex: 1, minWidth: 0 },
  invoiceSectionLabel: {
    color: '#64748b',
    fontSize: 9,
    fontWeight: '800',
    marginBottom: 6,
  },
  billPartyName: {
    color: '#020617',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 4,
  },
  invoiceBodyText: {
    color: '#475569',
    fontSize: 10,
    lineHeight: 16,
    marginTop: 3,
  },
  paymentBanner: {
    backgroundColor: '#f0fdfa',
    borderWidth: 1,
    borderColor: '#99f6e4',
    borderRadius: 8,
    paddingHorizontal: 11,
    paddingVertical: 10,
    marginVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  paymentSource: { color: '#334155', fontSize: 10 },
  paymentSourceValue: {
    color: '#020617',
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  paymentStatusBadge: {
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  invoiceItemsTable: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginTop: 7,
    marginBottom: 15,
  },
  invoiceItemsHeader: {
    backgroundColor: '#0f172a',
    paddingVertical: 9,
    paddingHorizontal: 7,
    flexDirection: 'row',
    alignItems: 'center',
  },
  invoiceItemsRow: {
    paddingVertical: 10,
    paddingHorizontal: 7,
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  },
  invoiceTableHeaderText: {
    color: '#fff',
    fontSize: 8,
    fontWeight: '700',
    flex: 1,
    textAlign: 'right',
  },
  invoiceItemText: {
    color: '#334155',
    fontSize: 8,
    lineHeight: 13,
    flex: 1,
    textAlign: 'right',
  },
  invoiceItemName: { flex: 2, textAlign: 'left' },
  invoiceItemTotal: { color: '#0f172a', fontWeight: '800' },
  invoiceTotalsSection: {
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 14,
    gap: 14,
  },
  invoiceNote: { minHeight: 42 },
  invoiceTotals: { borderTopWidth: 0 },
  billLine: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  billStrongLine: {
    borderTopWidth: 1,
    borderTopColor: '#cbd5e1',
    borderBottomWidth: 1,
    borderBottomColor: '#cbd5e1',
    paddingVertical: 11,
    marginTop: 3,
  },
  billValue: {
    color: '#334155',
    fontSize: 10,
    fontWeight: '600',
    flexShrink: 1,
    textAlign: 'right',
  },
  billStrong: { fontSize: 14, color: '#0f172a', fontWeight: '800' },
  billPaid: { color: '#047857' },
  billDue: { color: '#be123c', fontWeight: '800' },
  invoiceFooterNote: {
    color: '#64748b',
    backgroundColor: '#f8fafc',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    fontSize: 9,
    lineHeight: 14,
    textAlign: 'center',
    paddingVertical: 12,
    marginTop: 14,
  },
  invoiceFooterActions: {
    paddingHorizontal: 12,
    paddingVertical: 11,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 7,
  },
  invoiceCloseAction: {
    minHeight: 38,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 9,
  },
  invoiceCloseText: { color: '#334155', fontSize: 10, fontWeight: '700' },
  invoiceDownloadAction: {
    minHeight: 38,
    paddingHorizontal: 10,
    flexDirection: 'row',
    gap: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f9f93',
    borderRadius: 9,
  },
  invoiceDownloadText: { color: '#fff', fontSize: 10, fontWeight: '700' },
});
