import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F8FAFC' },
  pageContent: { padding: 14, paddingBottom: 40 },
  panel: { overflow: 'hidden', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 15, backgroundColor: '#fff' },
  panelHeader: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 15, borderBottomWidth: 1, borderBottomColor: '#E2E8F0', backgroundColor: '#fff' },
  flexOne: { flex: 1, minWidth: 0 },
  pageTitle: { color: '#0F172A', fontSize: 19, fontWeight: '800' },
  mutedText: { color: '#64748B', fontSize: 12, lineHeight: 17, marginTop: 4 },
  contentInset: { padding: 13, gap: 12 },
  primaryButton: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, paddingHorizontal: 13, borderWidth: 1, borderColor: '#0D9488', borderRadius: 10, backgroundColor: '#0D9488' },
  primaryButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  fullButton: { alignSelf: 'stretch' },
  formField: { gap: 6 },
  fieldLabel: { color: '#334155', fontSize: 12, fontWeight: '600' },
  selectButton: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingHorizontal: 11, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 9, backgroundColor: '#F8FAFC' },
  selectValue: { flex: 1, color: '#334155', fontSize: 12 },
  selectOptions: { maxHeight: 220, marginTop: 5, padding: 4, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 9, backgroundColor: '#fff' },
  selectOption: { minHeight: 38, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingHorizontal: 9, borderRadius: 7 },
  selectOptionActive: { backgroundColor: '#F0FDFA' },
  textInput: { minHeight: 42, paddingHorizontal: 11, paddingVertical: 9, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 9, color: '#0F172A', backgroundColor: '#fff', fontSize: 13 },
  textArea: { minHeight: 100, textAlignVertical: 'top' },
  loading: { minHeight: 110, alignItems: 'center', justifyContent: 'center', gap: 9 },
  listGap: { gap: 10 },
  dataCard: { gap: 10, padding: 13, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, backgroundColor: '#fff' },
  cardTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 9 },
  cardTitle: { color: '#0F172A', fontSize: 15, fontWeight: '700' },
  statusBadge: { alignSelf: 'flex-start', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 14 },
  statusBadgeTeal: { backgroundColor: '#CCFBF1' },
  statusBadgeMuted: { backgroundColor: '#F1F5F9' },
  statusBadgeSuccess: { backgroundColor: '#DCFCE7' },
  statusText: { fontSize: 10, fontWeight: '700' },
  statusTextTeal: { color: '#0F766E' },
  statusTextMuted: { color: '#475569' },
  statusTextSuccess: { color: '#15803D' },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  detailCell: { flexGrow: 1, flexBasis: '43%', minWidth: 110, padding: 9, borderRadius: 8, backgroundColor: '#F8FAFC' },
  detailLabel: { color: '#64748B', fontSize: 10 },
  detailValue: { color: '#0F172A', fontSize: 12, fontWeight: '600', marginTop: 3 },
  actionRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 2 },
  flexButton: { flex: 1 },
  outlineButton: { minHeight: 39, flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 10, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 9, backgroundColor: '#fff' },
  outlineButtonText: { color: '#334155', fontSize: 11, fontWeight: '700' },
  iconButton: { width: 40, height: 39, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 9, backgroundColor: '#fff' },
  emptyCard: { alignItems: 'center', gap: 8, margin: 14, padding: 20, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, backgroundColor: '#fff' },
  modalBackdrop: { flex: 1, justifyContent: 'center', padding: 17, backgroundColor: 'rgba(15,23,42,0.62)' },
  formModalCard: { height: '88%', maxHeight: '94%', flexShrink: 1, overflow: 'hidden', borderRadius: 16, backgroundColor: '#F8FAFC' },
  featureModalCard: { height: '92%', maxHeight: '96%', flexShrink: 1, overflow: 'hidden', borderRadius: 16, backgroundColor: '#F8FAFC' },
  modalHeader: { paddingHorizontal: 15, paddingTop: 16, paddingBottom: 13, borderBottomWidth: 1, borderBottomColor: '#E2E8F0', backgroundColor: '#F0FDFA' },
  modalClose: { position: 'absolute', zIndex: 2, top: 7, right: 7, width: 30, height: 30, alignItems: 'center', justifyContent: 'center' },
  modalTitle: { paddingRight: 28, color: '#0F172A', fontSize: 17, fontWeight: '800' },
  modalScroll: { flex: 1, minHeight: 0 },
  formBody: { gap: 13, padding: 15, paddingBottom: 22 },
  modalFooter: { flexDirection: 'row', gap: 8, padding: 11, borderTopWidth: 1, borderTopColor: '#E2E8F0', backgroundColor: '#fff' },
  searchBox: { minHeight: 43, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 11, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 9, backgroundColor: '#fff' },
  searchInput: { flex: 1, minWidth: 0, minHeight: 41, paddingVertical: 7, color: '#0F172A', fontSize: 12 },
  tabRow: { flexDirection: 'row', gap: 8 },
  tabButton: { minHeight: 38, flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8, borderWidth: 1, borderColor: '#DCE5E9', borderRadius: 9, backgroundColor: '#fff' },
  tabButtonActive: { borderColor: '#0D9488', backgroundColor: '#0D9488' },
  tabText: { color: '#475569', fontSize: 11, fontWeight: '700' },
  tabTextActive: { color: '#fff' },
  errorCard: { gap: 9, padding: 12, borderWidth: 1, borderColor: '#FECACA', borderRadius: 10, backgroundColor: '#FEF2F2' },
  errorText: { color: '#B91C1C', fontSize: 12 },
  approvalDetails: { display: 'flex', gap: 5, padding: 10, borderRadius: 9, backgroundColor: '#F8FAFC' },
  dangerOutlineButton: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 10, borderWidth: 1, borderColor: '#FECDD3', borderRadius: 9, backgroundColor: '#FFF1F2' },
  dangerText: { color: '#E11D48', fontSize: 12, fontWeight: '700' },
  dangerButton: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#E11D48', borderRadius: 9, backgroundColor: '#E11D48' },
  dangerButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
});

