import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  content: {
    padding: 16,
    paddingBottom: 80,
  },

  // Top Page Banner Header (Matches ClinicsManagementScreen & Web)
  bannerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    gap: 10,
  },
  bannerTitleBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#E6F4F1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
  },
  bannerSubtitle: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 2,
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0D9488',
    paddingHorizontal: 12,
    height: 38,
    borderRadius: 8,
    justifyContent: 'center',
  },
  addBtnText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 13,
  },

  // 4 Overview Metric Cards (Exact match with ClinicsManagementScreen)
  metricGrid4: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  metricGridMobile: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  metricCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  metricCardDesktop: {
    width: '23.8%',
  },
  metricCardMobile: {
    width: '48.5%',
    padding: 10,
  },
  metricIconBox: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
  },
  metricLabel: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '600',
    marginTop: 1,
  },

  // Search and Filter Bar (Matches ClinicsManagementScreen)
  searchFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 42,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: '#0F172A',
  },

  statusTriggerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 14,
    height: 42,
    minWidth: 130,
  },
  statusTriggerBtnText: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '600',
  },
  statusDropdownMenu: {
    position: 'absolute',
    top: 46,
    right: 0,
    minWidth: 150,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingVertical: 4,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    zIndex: 99,
  },
  statusDropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  statusDropdownItemText: {
    fontSize: 13,
    color: '#334155',
  },

  // Table Card Container
  tableCardContainer: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    marginBottom: 20,
  },
  tableHeaderBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    flexWrap: 'wrap',
    gap: 8,
  },
  tableHeaderLeft: {
    flex: 1,
    minWidth: 140,
  },
  tableHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tableTitleText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
  },
  tableSubtitleText: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  columnsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 7,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: '#FFFFFF',
  },
  columnsBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#334155',
  },
  refreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 7,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: '#FFFFFF',
  },
  refreshBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#334155',
  },
  lastRefreshedBar: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: '#F8FAFC',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  lastRefreshedLabel: {
    fontSize: 10,
    color: '#94A3B8',
  },

  // Loading & Empty States
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 36,
    gap: 8,
  },
  loadingText: {
    fontSize: 13,
    color: '#64748B',
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 40,
    gap: 6,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F172A',
  },
  emptySubtitle: {
    fontSize: 12,
    color: '#64748B',
    textAlign: 'center',
  },

  // Single Mobile Bill Card (Exact match with screenshot 2)
  mobileBillCard: {
    width: '100%',
    alignSelf: 'stretch',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    padding: 14,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  billNumberBlock: {
    flex: 1,
  },
  billNumberText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  patientNameText: {
    fontSize: 13,
    color: '#475569',
    marginTop: 2,
  },

  // Status Pill Badge (Matches screenshot 2)
  statusPillBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: '700',
  },

  // Card Middle Row: TOTAL & PHONE
  cardGridRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F1F5F9',
    paddingVertical: 10,
    marginVertical: 10,
  },
  gridCol: {
    flex: 1,
  },
  gridColLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  gridColVal: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
    marginTop: 2,
  },
  gridColValPhone: {
    fontSize: 13,
    color: '#0F172A',
    marginTop: 2,
  },

  // Card Bottom Row: Date, Payment mode, [Eye] [?]
  cardBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  metaBottomBlock: {
    flex: 1,
  },
  metaDateText: {
    fontSize: 12,
    color: '#64748B',
  },
  metaPaymentText: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  actionsBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  eyeActionBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#99F6E4',
    backgroundColor: '#F0FDFA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  moreActionBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Desktop Table Structure
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  thCell: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  tableBodyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  billNumberTableText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  patientNameTableText: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '600',
  },
  tdText: {
    fontSize: 12,
    color: '#334155',
  },

  // 3-Dots Action Menu Overlay (Screenshot 1 parity - anchored above 3-dots)
  actionMenuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.12)',
  },
  actionMenuCard: {
    position: 'absolute',
    width: 220,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingVertical: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  actionMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  actionMenuIcon: {
    marginRight: 10,
  },
  actionMenuText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0F172A',
  },
  actionMenuItemCancel: {
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    marginTop: 2,
  },
  actionMenuTextCancel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#DC2626',
  },

  paginationWrapper: {
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },

  // Modals Styling (Web-style Centered Dialog Modals, NOT bottom sheets)
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    width: '100%',
    maxWidth: 620,
    maxHeight: '90%',
    paddingBottom: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 12,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#0F172A',
  },
  modalSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  modalCloseBtn: {
    padding: 4,
  },
  modalScroll: {
    padding: 18,
    gap: 16,
  },
  formSection: {
    gap: 8,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  selectedPatientBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F0FDFA',
    borderWidth: 1,
    borderColor: '#99F6E4',
    borderRadius: 8,
    padding: 10,
  },
  patientSelectedLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  selectedPatientName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  selectedPatientSub: {
    fontSize: 12,
    color: '#0F766E',
    marginTop: 1,
  },
  clearPatientBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    padding: 4,
  },
  clearPatientBtnText: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '700',
  },
  patientSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: 10,
    height: 42,
    gap: 8,
  },
  patientSearchInput: {
    flex: 1,
    fontSize: 13,
    color: '#0F172A',
  },
  suggestionsContainer: {
    maxHeight: 160,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    marginTop: 4,
    backgroundColor: '#FFFFFF',
  },
  suggestionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  suggestionName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  suggestionPhone: {
    fontSize: 11,
    color: '#64748B',
  },
  apptChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#F1F5F9',
    marginRight: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  apptChipSelected: {
    backgroundColor: '#F0FDFA',
    borderColor: '#0D9488',
  },
  apptChipText: {
    fontSize: 12,
    color: '#475569',
    fontWeight: '600',
  },
  apptChipTextSelected: {
    color: '#0D9488',
    fontWeight: '800',
  },
  addItemBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#F0FDFA',
    borderWidth: 1,
    borderColor: '#99F6E4',
  },
  addItemBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0D9488',
  },
  itemRowCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 10,
    gap: 8,
  },
  itemCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  serviceNameInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 13,
    color: '#0F172A',
  },
  deleteRowBtn: {
    padding: 4,
  },
  itemCardInputs: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
  },
  inputCol: {
    flex: 1,
  },
  inputColTotal: {
    flex: 1.2,
    alignItems: 'flex-end',
  },
  inputColLabel: {
    fontSize: 10,
    color: '#64748B',
    fontWeight: '700',
    marginBottom: 2,
  },
  numericInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 5,
    fontSize: 12,
    color: '#0F172A',
    textAlign: 'center',
  },
  itemTotalDisplay: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 6,
  },
  summaryBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
    gap: 6,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  summaryLabel: {
    fontSize: 13,
    color: '#475569',
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  grandTotalRow: {
    borderTopWidth: 1,
    borderTopColor: '#CBD5E1',
    paddingTop: 8,
    marginTop: 4,
  },
  grandTotalLabel: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F172A',
  },
  grandTotalValue: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0D9488',
  },
  subFieldLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
    marginBottom: 4,
  },
  methodsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  methodChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  methodChipSelected: {
    backgroundColor: '#0D9488',
    borderColor: '#0D9488',
  },
  methodChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  methodChipTextSelected: {
    color: '#FFFFFF',
  },
  paymentInputRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-end',
  },
  paidInputField: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 15,
    fontWeight: '800',
    color: '#0F172A',
  },
  quickPayBtnCol: {
    flexDirection: 'row',
    gap: 6,
  },
  quickPayBtn: {
    backgroundColor: '#F0FDFA',
    borderWidth: 1,
    borderColor: '#99F6E4',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
  },
  quickPayBtnText: {
    color: '#0D9488',
    fontWeight: '800',
    fontSize: 12,
  },
  statusPreviewBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 6,
    padding: 8,
    marginTop: 8,
  },
  statusPreviewLabel: {
    fontSize: 12,
    color: '#475569',
  },
  statusPreviewBalance: {
    fontSize: 12,
    fontWeight: '700',
    color: '#EA580C',
  },
  noteInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: '#0F172A',
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 18,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  modalCancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    alignItems: 'center',
  },
  modalCancelBtnText: {
    color: '#475569',
    fontWeight: '700',
    fontSize: 14,
  },
  modalSubmitBtn: {
    flex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#0D9488',
    paddingVertical: 12,
    borderRadius: 8,
  },
  modalSubmitBtnText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 14,
  },

  // Receipt Modal Styles
  receiptHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  invoiceReceiptContent: {
    padding: 16,
    gap: 14,
  },
  invoiceTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingBottom: 14,
    borderBottomWidth: 2,
    borderBottomColor: '#0D9488',
  },
  invoiceType: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0D9488',
    textAlign: 'right',
  },
  invoiceSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748B',
    marginTop: 2,
  },
  paymentStatusBanner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F0FDFA',
    borderWidth: 1,
    borderColor: '#CCFBF1',
    borderRadius: 8,
    padding: 12,
  },
  paymentStatusText: { fontSize: 12, color: '#0F172A' },
  paymentStatusLabel: { fontSize: 11, fontWeight: '800' },
  paidLabel: { color: '#16A34A' },
  dueLabel: { color: '#B45309' },
  invoiceSummaryLayout: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  invoiceNotes: { flex: 1, gap: 8, paddingTop: 4 },
  invoicePdfFooter: {
    alignItems: 'center',
    gap: 12,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#CBD5E1',
  },
  invoiceFooterNote: { fontSize: 10, color: '#64748B', textAlign: 'center' },
  invoiceDownloadButton: {
    minHeight: 48,
    width: '100%',
    borderRadius: 8,
    backgroundColor: '#0D9488',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  invoiceDownloadButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  clinicBrandingName: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
  },
  clinicBrandingAddress: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  clinicBrandingContact: {
    fontSize: 11,
    color: '#94A3B8',
    marginTop: 2,
  },
  receiptMetaGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  metaCol: {
    flex: 1,
  },
  metaHeader: {
    fontSize: 10,
    fontWeight: '800',
    color: '#94A3B8',
    textTransform: 'uppercase',
  },
  metaPatientName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
    marginVertical: 2,
  },
  metaBillNo: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0D9488',
    marginVertical: 2,
  },
  metaSub: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 1,
  },
  receiptTableContainer: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
  },
  receiptTableHeader: {
    flexDirection: 'row',
    backgroundColor: '#0F172A',
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  receiptTh: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  receiptTableRow: {
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    alignItems: 'center',
  },
  receiptItemTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0F172A',
  },
  receiptItemCode: {
    fontSize: 10,
    color: '#94A3B8',
  },
  receiptTd: {
    fontSize: 12,
    color: '#475569',
  },
  receiptTdTotal: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
  },
  receiptSummaryCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    padding: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  receiptSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  receiptSumLabel: {
    fontSize: 12,
    color: '#475569',
  },
  receiptSumVal: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0F172A',
  },
  receiptGrandRow: {
    borderTopWidth: 1,
    borderTopColor: '#CBD5E1',
    paddingTop: 6,
    marginTop: 2,
  },
  receiptGrandLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  receiptGrandVal: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0D9488',
  },
  stampRow: {
    alignItems: 'center',
    marginVertical: 6,
  },
  receiptStamp: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1.5,
  },
  receiptStampText: {
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1,
  },
  receiptStampPaid: {
    backgroundColor: '#DCFCE7',
    borderColor: '#16A34A',
  },
  receiptStampPartial: {
    backgroundColor: '#DBEAFE',
    borderColor: '#1E40AF',
  },
  receiptStampPending: {
    backgroundColor: '#FEF3C7',
    borderColor: '#92400E',
  },
  receiptStampCancelled: {
    backgroundColor: '#FEE2E2',
    borderColor: '#991B1B',
  },

  // Record Payment Modal
  paymentModalScroll: {
    padding: 18,
    gap: 10,
  },
  paymentMetaBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
    gap: 6,
  },
  paymentMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  paymentMetaLabel: {
    fontSize: 12,
    color: '#64748B',
  },
  paymentMetaValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  paymentDueRow: {
    borderTopWidth: 1,
    borderTopColor: '#CBD5E1',
    paddingTop: 6,
    marginTop: 2,
  },
  paymentDueLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: '#EA580C',
  },
  paymentDueValue: {
    fontSize: 15,
    fontWeight: '900',
    color: '#EA580C',
  },

  // -- WEB CREATE BILL MODAL STYLES (Screenshot 1, 2, 3 parity) ------------
  webCreateModalContainer: {
    maxWidth: 500,
    width: '100%',
    maxHeight: '94%',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingBottom: 0,
  },
  webModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  webHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  webHeaderIconBox: {
    width: 36,
    height: 36,
    borderRadius: 9,
    backgroundColor: '#0D9488',
    alignItems: 'center',
    justifyContent: 'center',
  },
  webModalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
  },
  webModalSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  webModalCloseBtn: {
    padding: 6,
    borderRadius: 8,
  },
  webModalScroll: {
    padding: 16,
    paddingBottom: 20,
  },
  webFormSection: {
    gap: 4,
  },
  webSectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  webSectionIconBox: {
    width: 30,
    height: 30,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  webSectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  webSectionSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 1,
  },
  webSectionDivider: {
    height: 1,
    backgroundColor: '#F1F5F9',
    marginVertical: 14,
  },
  webFieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: 6,
  },
  webSearchInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#0D9488',
    borderRadius: 9,
    paddingHorizontal: 12,
  },
  webSearchInputField: {
    flex: 1,
    paddingVertical: 10,
    fontSize: 13,
    color: '#0F172A',
  },
  webSelectBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  webSelectValue: {
    fontSize: 13,
    color: '#0F172A',
    fontWeight: '500',
    flex: 1,
    marginRight: 6,
  },
  webHelperText: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 5,
  },
  webDropdownMenu: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    marginTop: 4,
    maxHeight: 180,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 6,
    overflow: 'hidden',
  },
  webDropdownItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F8FAFC',
  },
  webDropdownItemSelected: {
    backgroundColor: '#F0FDFA',
  },
  webDropdownItemText: {
    fontSize: 13,
    color: '#334155',
  },
  webTextarea: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: '#0F172A',
    minHeight: 70,
    textAlignVertical: 'top',
  },
  webAddServiceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginTop: 8,
    gap: 6,
  },
  webAddServiceBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  webInputField: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: '#0F172A',
  },
  webEmptyServiceBox: {
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    paddingVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  webEmptyServiceText: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '500',
  },
  webSummaryCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 14,
    marginTop: 8,
  },
  webSummaryLabel: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
  },
  webSummaryValue: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 2,
  },
  webModalFooter: {
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
  },
  webAmountDueRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  webAmountDueLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: 0.5,
  },
  webAmountDueValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
  },
  webFooterBtnsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  webCancelBtn: {
    flex: 1,
    height: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  webCancelBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0F172A',
  },
  webCreateBillBtn: {
    flex: 1,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#0D9488',
    alignItems: 'center',
    justifyContent: 'center',
  },
  webCreateBillBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  webInlineError: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  webInlineErrorText: {
    fontSize: 11,
    color: '#EF4444',
    fontWeight: '500',
  },
  rxBadge: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  rxBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
  },
  rxNoticeText: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 6,
  },
  rxCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
  },
  rxCardTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0D9488',
  },
  rxCardMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 4,
    gap: 4,
  },
  rxCardMetaText: {
    fontSize: 11,
    color: '#64748B',
  },
  rxCardMetaBold: {
    fontWeight: '600',
    color: '#334155',
  },
  rxDetailText: {
    fontSize: 12,
    color: '#334155',
    marginTop: 3,
  },
  rxPillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  rxPill: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  rxPillText: {
    fontSize: 11,
    fontWeight: '600',
  },
  serviceFormBox: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  serviceFormHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  serviceFormTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  serviceFormInputLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 4,
  },
  serviceFormInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    fontSize: 12,
    color: '#0F172A',
  },
  serviceFormGrid: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  serviceAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0D9488',
    borderRadius: 6,
    paddingVertical: 9,
    paddingHorizontal: 16,
    marginTop: 12,
    gap: 6,
  },
  serviceAddBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  itemsListTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  addedItemCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    padding: 10,
  },
  addedItemCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addedItemTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  addedItemSubtitle: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 1,
  },
  addedItemDeleteBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: '#FEF2F2',
  },
  addedItemGrid: {
    flexDirection: 'row',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  addedItemGridCol: {
    flex: 1,
  },
  addedItemColLabel: {
    fontSize: 10,
    color: '#64748B',
    fontWeight: '500',
  },
  addedItemColVal: {
    fontSize: 12,
    color: '#0F172A',
    fontWeight: '600',
    marginTop: 2,
  },
  addedItemColTotal: {
    fontSize: 13,
    color: '#0D9488',
    fontWeight: '700',
    marginTop: 2,
  },

  extractedInline1: { marginRight: 4 },
  extractedInline2: { marginLeft: 12, flex: 1 },
  extractedInline3: { backgroundColor: '#CCFBF1' },
  extractedInline4: { fontSize: 16 },
  extractedInline5: { fontSize: 11 },
  extractedInline6: { backgroundColor: '#DCFCE7' },
  extractedInline7: { backgroundColor: '#DBEAFE' },
  extractedInline8: { backgroundColor: '#FEF3C7' },
  extractedInline9: { flexDirection: 'column', alignItems: 'stretch' },
  extractedInline10: { marginRight: 8 },
  extractedInline11: { position: 'relative', zIndex: 20 },
  extractedInline12: {
    color: '#0D9488',
    fontWeight: '700',
  },
  extractedInline13: { flexDirection: 'row', alignItems: 'center' },
  extractedInline14: { marginRight: 6 },
  extractedInline15: { padding: 12, gap: 12 },
  extractedInline16: { color: '#166534' },
  extractedInline17: { color: '#DC2626' },
  extractedInline18: { width: 180 },
  extractedInline19: { width: 140 },
  extractedInline20: { width: 120 },
  extractedInline21: { width: 130 },
  extractedInline22: { width: 140, textAlign: 'center' },
  extractedInline23: { width: 90, textAlign: 'right' },
  extractedInline24: { width: 180, justifyContent: 'center' },
  extractedInline25: { width: 140, justifyContent: 'center' },
  extractedInline26: { width: 120, justifyContent: 'center' },
  extractedInline27: { width: 130, justifyContent: 'center' },
  extractedInline28: { fontWeight: '700' },
  extractedInline29: { color: '#166534', fontWeight: '600' },
  extractedInline30: {
    width: 140,
    alignItems: 'center',
    justifyContent: 'center',
  },
  extractedInline31: {
    width: 90,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  extractedInline32: { maxHeight: '94%' },
  extractedInline33: { padding: 40, alignItems: 'center' },
  extractedInline34: { marginTop: 8, color: '#64748B' },
  extractedInline35: { flex: 1 },
  extractedInline36: { alignItems: 'flex-end' },
  extractedInline37: { fontWeight: '800' },
  extractedInline38: { flex: 0.3 },
  extractedInline39: { flex: 1.8 },
  extractedInline40: { flex: 0.45, textAlign: 'center' },
  extractedInline41: { flex: 0.9, textAlign: 'right' },
  extractedInline42: { flex: 0.5, textAlign: 'right' },
  extractedInline43: { flex: 1, textAlign: 'right' },
  extractedInline44: { color: '#16A34A' },
  extractedInline45: { color: '#DC2626', fontWeight: '800' },
  extractedInline46: { color: '#1E40AF' },
  extractedInline47: { color: '#92400E' },
  extractedInline48: { color: '#991B1B' },
  extractedInline49: { maxHeight: '60%' },
  metricValueCell: { flex: 1 },
  metricValueCellMobile: { marginLeft: 8 },
  metricValueCellDesktop: { marginLeft: 12 },
  dueAmountDanger: { color: '#DC2626' },
  dueAmountNormal: { color: '#0F172A' },
  pendingAmountDanger: { color: '#DC2626', fontWeight: '600' },
  pendingAmountNormal: { color: '#64748B', fontWeight: '600' },
});
