/**
 * @deprecated Compatibility exports for legacy screens.
 *
 * Every icon now comes from lucide-react-native. New screens should import the
 * needed Lucide icon directly from "lucide-react-native"; this module remains
 * only while the existing screen imports are migrated incrementally.
 */
export {
  Activity as ActivityPulseIcon,
  AlertCircle as AlertCircleIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUpRight as ArrowUpRightIcon,
  Banknote as BillBanknoteIcon,
  BadgeIndianRupee as IndianRupeeIcon,
  Bell as BellNotificationIcon,
  Bell as DrawerBellIcon,
  Building2 as BuildingClinicIcon,
  Building as InPersonClinicIcon,
  Calendar as CalendarIcon,
  CalendarClock as CalendarClockIcon,
  CalendarDays as DrawerCalendarIcon,
  CalendarPlus as CalendarPlusIcon,
  CheckCircle2 as CheckCircleIcon,
  ChevronDown as ChevronDownIcon,
  ChevronsUpDown as ChevronsUpDownIcon,
  CircleAlert as BillingAlertCancelIcon,
  CircleDollarSign as BillingPaymentCardIcon,
  ClipboardCheck as ClipboardCheckIcon,
  Clock3 as ClockOutlineIcon,
  Columns3 as ColumnsIcon,
  CreditCard as DrawerCreditCardIcon,
  Download as DownloadIcon,
  Edit3 as EditPenIcon,
  Eye as BillingEyeIcon,
  FileCheck2 as ClinicVerifiedIcon,
  FileHeart as MedicalHistoryIcon,
  FilePenLine as EditBillDollarIcon,
  FilePlus2 as EnvelopePlusIcon,
  FileText as BillInfoDocIcon,
  FileText as ReportDocIcon,
  FilterX as FilterResetIcon,
  FlaskConical as DrawerFlaskIcon,
  TestTube as LabTestTubeIcon,
  TestTube as LabTubeIcon,
  TestTube,
  Globe2 as GlobeCareIcon,
  HeartPulse as LabPulseIcon,
  LayoutDashboard as DashboardIcon,
  LayoutGrid as DrawerGridIcon,
  LogOut as DrawerLogoutIcon,
  Mail as BillingMailIcon,
  MapPin as MapPinIcon,
  Menu as HamburgerMenuIcon,
  MessageCircle as BillingWhatsAppIcon,
  MoreVertical as MoreVerticalIcon,
  Package as InventoryPackageIcon,
  Pencil as PenEditIcon,
  PhoneCall as PhoneCallIcon,
  Pill as DrawerPillIcon,
  Pill as MedicinePillIcon,
  Pill as TiltedCapsuleIcon,
  Plus as UserPlusIcon,
  Receipt as BillingCardIcon,
  Receipt as ReceiptBillIcon,
  Receipt as ReceiptIcon,
  Receipt,
  ReceiptText as ReceiptTextIcon,
  RefreshCw as InventoryRefreshIcon,
  RefreshCw as RefreshCwIcon,
  Search as SearchIcon,
  Search as SearchInputIcon,
  Send as ShareLinkIcon,
  ShieldCheck as ShieldCheckIcon,
  Sparkles as SparklesIcon,
  Stethoscope as StethoscopeIcon,
  TestTubeDiagonal as LabReportsIcon,
  Trash2 as BillTrashIcon,
  Trash2 as LabTrashIcon,
  TriangleAlert as InventoryAlertTriangleIcon,
  User as PatientUserIcon,
  UserCheck as ViewDetailsIcon,
  UserRoundCheck as PrescriptionIcon,
  Users as DrawerUsersIcon,
  Users as LabPatientsIcon,
  Users as LabUsersIcon,
  Users as UsersIcon,
  Video as DrawerVideoIcon,
  Video as VideoCallIcon,
  Video as VideoCamIcon,
  Wallet as WalletOutlineIcon,
  WalletCards as BillingSlidersIcon,
  WalletMinimal as InventoryRupeeIcon,
  WalletMinimal as RupeeIcon,
  XCircle as CancelCircleCrossIcon,
} from "lucide-react-native";
